# esankhyiki - Examples

Python client for India's National Statistical Office (MoSPI) data portal.
Access indicators across 22 datasets: employment, prices, GDP, health, education, environment, and more.

```bash
pip install mospi-esankhyiki[pandas]
```

In [1]:
import warnings
warnings.filterwarnings('ignore')
import esankhyiki
from esankhyiki.exceptions import InvalidDatasetError, InvalidFilterError, APIError, NoDataError

---
## Available Datasets

In [2]:
esankhyiki.list_datasets(format="df")

     dataset
0       PLFS
1        CPI
2        IIP
3        ASI
4        NAS
5        WPI
6     ENERGY
7      AISHE
8      ASUSE
9     GENDER
10      NFHS
11  ENVSTATS
12       RBI
13   CPIALRL
14      HCES
15       TUS
16        EC
17     UDISE
18      MNRE
19       ISP
20     NSS71
21    NSS71E
22     NSS72
23    NSS72T
24     NSS73
25     NSS74
26     NSS75
27    NSS75E
28     NSS76
29    NSS76C
30     NSS77
31     NSS78
32     NSS79
33     NSS80
34    NSS80C

---
## NSS-71 Education in India (NSS 71st Round)

The surveys on Social Consumption relating to Education, conducted by the National Sample Survey Office (NSSO), are the primary sources of data on various indicators on education scenario of the country, like literacy rates, attendance ratios, incentives received by the students, expenditure incurred for the purpose of education, etc. These are used for planning, policy formulation, and decision support and as input for further analytical studies by various Government organizations, academicians, researchers and scholars

In [ ]:
# Indicators List for NSS-71 dataset
esankhyiki.get_indicators("NSS71E", format="df")

In [ ]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS71E", indicator_code=6)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

In [ ]:
# get data return full data according to filter
esankhyiki.get_data("NSS71E", {
  "survey_code": 1,
  "indicator_code": 6,
  "state_code": 1,
  "sector_code": 2,
  "gender_code": 2,
  "level_of_education_code":3,
}, format="df")

---
## NSS-71 Health in India (NSS 71st Round)

The surveys on Social Consumption relating to Health, conducted by the National Sample Survey Office (NSSO) are the primary source of data on basic quantitative information on the health sector like morbidity, hospitalization, extent of receipt of pre-natal and post-natal care by women, expenditure incurred on treatment received from health services in public and private sectors, use and cost of treatment by AYUSH, etc. These are used for planning, policy formulation, decision support and as input for further analytical studies by various Government organizations, academicians, researchers and scholars.

In [3]:
# Indicators List for NSS-71 dataset
esankhyiki.get_indicators("NSS71", format="df")

    indicator_code                                        description
0               15  Age-group wise cases of hospitalisation (EC) r...
1               45  Average medical and non-medical expenditure (R...
2               46  Average medical and non-medical expenditure (R...
3               29  Average medical expenditure (Rs.) per hospital...
4               34  Average total medical expenditure for (non-hos...
5               35  Average total medical expenditure for (non-hos...
6               36  Average total medical expenditure for (non-hos...
7               27  Average total medical expenditure for treatmen...
8               28  Average total medical expenditure per hospital...
9               33  Average total medical expenditure (Rs.) for tr...
10              37  Break-up of average medical expenditure (Rs.) ...
11              18  Cases of hospitalisation (EC) on account of ai...
12              19  Cases of hospitalisation(EC) on account of ail...
13              13  Hospitalisation cases (EC) per 100,000 persons...
14              17  Hospitalisation cases (EC) per 100,000 persons...
15              14  Hospitalisation cases (EC) per 100,000 persons...
16              32  Number of persons per 1,00,000 reporting onset...
17              39  Per thousand distribution of aged persons of e...
18              38  Per thousand distribution of aged persons of e...
19              40  Per thousand distribution of cases of hospital...
20              42  Per thousand distribution of cases of hospital...
21              41  Per thousand distribution of cases of hospital...
22              43  Per thousand distribution of cases of hospital...
23              44  Per thousand distribution of cases of hospital...
24              26  Per thousand distribution of hospitalisation c...
25              25  Per thousand distribution of hospitalisation c...
26              24  Per thousand distribution of hospitalisation c...
27              22  Per thousand distribution of hospitalisation c...
28              23  Per thousand distribution of hospitalisation c...
29              16  Per thousand distribution of hospitalised case...
30              21  Per thousand distribution of hospitalised case...
31              20  Per thousand distribution of hospitalised case...
32              30  Per thousand distribution of spells of ailment...
33              31  Per thousand distribution of spells of ailment...

In [4]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS71", indicator_code=15)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

state (1 values):
  {'state_code': 37, 'description': 'All-India'}

sector (3 values):
  {'sector_code': 1, 'description': 'Rural'}
  {'sector_code': 2, 'description': 'Urban'}
  {'sector_code': 4, 'description': 'All'}

gender (3 values):
  {'gender_code': 1, 'description': 'Male'}
  {'gender_code': 2, 'description': 'Female'}
  {'gender_code': 4, 'description': 'All'}

age_group (18 values):
  {'age_group_code': 39, 'description': '0-14'}
  {'age_group_code': 1, 'description': '0-4'}
  {'age_group_code': 7, 'description': '10-14'}
  {'age_group_code': 11, 'description': '15-19'}
  {'age_group_code': 13, 'description': '15-29'}

In [5]:
# get data return full data according to filter
esankhyiki.get_data("NSS71", {
  "survey_code": 2,
  "indicator_code": 15,
  "state_code": 37,
  "sector_code": 2,
  "gender_code": 2,
  "age_group_code":1,
}, format="df")

================================================================================
URL: http://10.24.89.9:5000/api/nss-71/getNss71Records?survey_code=2&indicator_code=15&state_code=37&sector_code=2&gender_code=2&age_group_code=1
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"survey_period":null,"indicator":"Age-group wise cases of hospitalisation (EC) reported per 1000 persons during the last 365 days","state":"All-India","sector":"Urban","gender":"Female","age_group":"0-4","value":"39","unit":"Number"}],"meta_data":{"page":1,"totalRecords":1,"totalPages":1,"recordPerPage":10},"msg":"Data fetched successfully","statusCode":true}
================================================================================

,survey_period,indicator,state,sector,gender,age_group,value,unit
0,None,Age-group wise cases of hospitalisation (EC) r...,All-India,Urban,Female,0-4,39,Number

---
## NSS-72 Domestic Tourism in India (NSS 72nd Round)
The Census provides granular, ground-level data on all minor irrigation projects (both groundwater schemes like dug wells, shallow tube-wells, and deep tube-wells, and surface water schemes like surface flow and surface lift) across rural and urban India, detailing their operational status, irrigation potential created, and actual utilization.

In [ ]:
# Indicators List for NSS-72T dataset
esankhyiki.get_indicators("NSS72T", format="df")

In [ ]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS72T", indicator_code=1)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

In [ ]:
# get data return full data according to filter
esankhyiki.get_data("NSS72T", {
    "indicator_code": 1,
    "state_code": 4,
    "sector_code":1,
    "religion_code":1,
}, format="df")

---
## NSS-72 Household Expenditure on Services and Durable Goods (72nd Round)
This survey had two parts. One part was concerned with household expenditure on different types of consumer services and the other part related to expenditure by the households on durable goods. As household expenditure on services forms an important part of Private Final Consumption Expenditure (PFCE), this focused survey is expected to provide improved estimates of household expenditure on the services as compared to the same based on data collected through usual Consumer Expenditure Survey.

In [ ]:
# Indicators List for NSS-72 dataset
esankhyiki.get_indicators("NSS72", format="df")

In [ ]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS72", indicator_code=1)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

In [ ]:
# get data return full data according to filter
esankhyiki.get_data("NSS72", {
    "indicator_code": 1,
    "sector_code":1,
    "mode_of_transport_code": 1,
    "expenditure_component_code":1,
}, format="df")

---
## NSS - 73 Unincorporated Non-Agricultural Enterprises in India (NSS 73rd Round)
The Survey includes Unincorporated Non-Agricultural Enterprises in manufacturing, trade, non-captive electricity generation & transmission and other services sector (excluding construction).

In [ ]:
# Indicators  by survey_code
esankhyiki.get_indicators("NSS73", format="df")

In [ ]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS73", indicator_code=1)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

In [ ]:
# get data return full data according to filter
esankhyiki.get_data("NSS73", {
    "indicator_code": 1,
    "state_ut_code": 4,
    "sector_code":1,
    "broad_activity_category_code": 1,
    "enterprise_type_code":1,
    "activity_category_code": 1,
}, format="df")

---
## NSS-74 Services Sector Enterprises in India (NSS 74th Round)
The Survey generate estimates of various operational and economic characteristics of services sector enterprises (excluding financial sector).

In [ ]:
# Indicators List for NSS-74 dataset
esankhyiki.get_indicators("NSS74", format="df")

In [ ]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS74", indicator_code=1)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

In [ ]:
# get data return full data according to filter
esankhyiki.get_data("NSS74", {
  "indicator_code": 1,
  "broad_activity_code": 2,
  "frame_code": 1,
  "registration_status_code": 1
}, format="df")

---
## NSS - 75E Household Social Consumption on Education in India (NSS 75th Round)
The surveys of social consumption relating to education, conducted by the National Statistical Office (NSO) is the primary source of data for generating various indicators on education like, level of education, attendance, incentives received by the students, expenditure on education, etc.

In [ ]:
# Indicators  by survey_code
esankhyiki.get_indicators("NSS75E", format="df")

In [ ]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS75E", indicator_code=43)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

In [ ]:
# get data return full data according to filter
esankhyiki.get_data("NSS75E", {
    "indicator_code": 43,
    "survey_code":2,
    "state_code": 4,
    "sector_code":1,
    "gender_code": 1,
}, format="df")

---
## NSS - 75 Household Social Consumption on Health in India (NSS 75th Round)
The surveys of social consumption relating to Health, conducted by the National Statistical Office (NSO) is the primary source of data for generating various indicators.

In [ ]:
# Indicators  by survey_code
esankhyiki.get_indicators("NSS75", format="df")

In [ ]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS75E", indicator_code=30)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

In [ ]:
# get data return full data according to filter
esankhyiki.get_data("NSS75E", {
    "indicator_code": 30,
    "survey_code":1,
    "state_code": 4,
    "sector_code":1,
    "gender_code": 1,
}, format="df")

---
## NSS - 76 Drinking Water, Sanitation, Hygiene and Housing Condition in India (NSS 76th Round)
The objective of NSS 76th round from July to December 2018, is to examine and study different aspects of living conditions necessary for decent and healthy living of the household members by developing suitable indicators based on the information collected through the survey.

In [ ]:
# Indicators  by survey_code
esankhyiki.get_indicators("NSS76", format="df")

In [ ]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS76", indicator_code=16)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

In [ ]:
# get data return full data according to filter
esankhyiki.get_data("NSS76", {
    "indicator_code": 16,
    "survey_code":2,
    "state_code": 4,
    "sector_code":1,
    "quintile_class_code": 1,
    "households_percentage_code": 1,
}, format="df")

---
## NSS - 76C Persons with Disabilities in India (NSS 76th Round)
In NSS 76th round survey for classification of disabilities, all the specified disabilities stated in The Right of Persons with Disabilities Act, 2016 have been considered.

In [ ]:
# Indicators  by survey_code
esankhyiki.get_indicators("NSS76C", format="df")

In [ ]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS76C", indicator_code=12)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

In [ ]:
# get data return full data according to filter
esankhyiki.get_data("NSS76C", {
    "indicator_code": 12,
    "survey_code":1,
    "state_code": 4,
    "sector_code":1,
    "gender_code": 1,
    "use_of_public_transport_code": 1,
}, format="df")

---
## NSS - 80 Comprehensive Modular Survey: Telecom (CMST) (NSS 80th Round)
 Comprehensive Modular Survey: Telecom (CMST) from January to March 2025 collected data on various aspects of mobile and internet usage at both the household and individual levels. Additionally, information on selected ICT skills was also captured.

In [ ]:
# Indicators  by survey_code
esankhyiki.get_indicators("NSS80", format="df")

In [ ]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS80", indicator_code=12)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

In [ ]:
# get data return full data according to filter
esankhyiki.get_data("NSS80", {
    "indicator_code": 12,
    "survey_code":1,
    "state_code": 4,
    "sector_code":1,
    "gender_code": 1,
    "agegroup_code": 1,
}, format="df")

---
## NSS - 80C Comprehensive Modular Survey: Education (CMSE) (NSS 80th Round)
 Comprehensive Modular Survey: Education (CMSE) from April to June 2025 primarily collected expenditure-related information incurred by the student households enrolled in school education.

In [ ]:
# Indicators  by survey_code
esankhyiki.get_indicators("NSS80C", format="df")

In [ ]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS80C", indicator_code=29)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

In [ ]:
# get data return full data according to filter
esankhyiki.get_data("NSS80C", {
    "indicator_code": 29,
    "survey_code":2,
    "state_code": 4,
    "sector_code":1,
    "gender_code": 1,
    "type_of_school_code": 1,
}, format="df")

## ISP - Index of Services Production - Trial Series

Provides experimental estimates of service sector production across selected service industries.
Use `get_indicators` to view available indicator codes and `get_metadata` to retrieve valid filter values for a selected indicator.

In [ ]:
# Indicators List for ISP dataset
esankhyiki.get_indicators("ISP", format="df")

In [ ]:
metadata = esankhyiki.get_metadata("ISP", frequency_code=1)[0]

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values:
        print(v)

In [ ]:
esankhyiki.get_data(
    "ISP",
    {
        "frequency_code": 1,
        "year": "2025-26",
        "broad_sub_sector_code": 3,
    },
    format="df",
)

---
## PLFS - Periodic Labour Force Survey

Covers labour force participation, unemployment, worker population ratio, wages.
Use `get_indicators` to see what indicator codes are available, `get_metadata` to see valid filter values for a given indicator.

In [ ]:
# Indicators grouped by frequency_code
indicators = esankhyiki.get_indicators("PLFS")
for group, items in indicators["indicators_by_frequency"].items():
    print(f"\n{group}:")
    for item in items:
        print(f"  {item['indicator_code']}: {item.get('indicator_name', item.get('description', ''))}")

In [ ]:
# Valid filter values for Unemployment Rate (indicator_code=3), Annual (frequency_code=1)
metadata = esankhyiki.get_metadata("PLFS", indicator_code=3, frequency_code=1, year_type_code=1)
for key, values in metadata["filter_values"]["data"].items():
    print(f"\n{key}:")
    for v in values[:4]:
        print(f"  {v}")

In [ ]:
# Unemployment Rate - All India, all years, both sectors
esankhyiki.get_data("PLFS", {
    "indicator_code": 3,
    "frequency_code": 1,
    "year_type_code":1,
    "state_code": 99,     # 99 = All India
    "gender_code": 3,     # 3 = Person
    "age_code": 1,        # 1 = 15 years and above
    "sector_code": 3,     # 3 = rural + urban
}, format="df")

---
## CPI - Consumer Price Index

Multiple base years (2010, 2012, 2024) and two levels: Group and Item.

In [ ]:
# Available base years, levels, and series
esankhyiki.get_indicators("CPI", format="df")

In [ ]:
# Filter values for base_year=2012, Group level
metadata = esankhyiki.get_metadata("CPI", base_year="2012", level="Group", series="Current", format="df")
metadata

In [ ]:
# CPI Group index, base year 2012, year 2024
esankhyiki.get_data("CPI", {
    "base_year": "2012",
    "series": "Current",
    "year": "2024",
}, format="df")

---
## NAS - National Accounts Statistics (GDP)

Annual and quarterly GDP, GVA, consumption, capital formation by industry and institutional sector.

In [ ]:
# esankhyiki.get_indicators("NAS", format="df")
esankhyiki.get_indicators("NAS", account_code=2, format="df")

In [ ]:
# Filter values for GVA by industry (indicator_code=1), base year 2022-23
metadata = esankhyiki.get_metadata("NAS", indicator_code=1, base_year="2022-23", series="Current", frequency_code=1, account_code=1)
for key, values in metadata.items():
    if isinstance(values, list):
        print(f"{key}: {values[:10]}")

In [ ]:
# GVA by industry, current prices, latest estimates
esankhyiki.get_data("NAS", {
    "base_year":"2011-12",
    "series": "Current",
    "frequency_code": 1,
    "indicator_code": 25,
    "account_code": 2,
}, format="df")

---
## IIP - Index of Industrial Production

Monthly and annual industrial output across manufacturing, mining, and electricity sectors.

In [ ]:
# Available categories and years for IIP annual
metadata = esankhyiki.get_metadata("IIP", base_year="2011-12", frequency="Annually")
metadata

In [ ]:
# IIP annual, 2023-24
esankhyiki.get_data("IIP", {
    "base_year": "2011-12",
    "financial_year": "2023-24",
}, format="df")

---
## GENDER - Gender Statistics

147 indicators covering demographics, health, education, labour, financial inclusion, and crimes against women.

In [ ]:
indicators = esankhyiki.get_indicators("GENDER")
print(f"Total indicators: {len(indicators)}\n")
for i in indicators[:10]:
    print(f"  {i['indicator_code']}: {i['description']}")

In [ ]:
# Sex ratio (indicator_code=2)
esankhyiki.get_data("GENDER", {"indicator_code": 2}, format="df")

---
## ENVSTATS - Environment Statistics

124 indicators covering climate, water, forests, biodiversity, pollution, and natural disasters.

In [ ]:
indicators = esankhyiki.get_indicators("ENVSTATS")
print(f"Total indicators: {len(indicators)}\n")
for i in indicators[:10]:
    print(f"  {i['indicator_code']}: {i.get('description', i.get('label', ''))}")

In [ ]:
# Mean temperature trend (indicator_code=1)
esankhyiki.get_data("ENVSTATS", {"indicator_code": 1}, format="df")

---
## RBI - Foreign Trade and Exchange Rates

39 indicators on balance of payments, forex reserves, exchange rates (155 currencies), NRI deposits.

In [ ]:
indicators = esankhyiki.get_indicators("RBI")
for i in indicators:
    print(f"  {i['indicator_code']}: {i['label']}")

In [ ]:
# Get valid sub_indicator_codes for Balance of Payments (indicator_code=22)
metadata = esankhyiki.get_metadata("RBI", sub_indicator_code=22)
metadata

In [ ]:
# Balance of Payments
esankhyiki.get_data("RBI", {"indicator_code": 22}, format="df")

---
## EC - Economic Census

District-level establishment and worker counts across three census editions (EC4/EC5/EC6).

In [ ]:
esankhyiki.get_indicators("EC", format="df")

In [ ]:
# EC6 (2013-14) - available states and filter options
metadata = esankhyiki.get_metadata("EC", indicator_code=1)
metadata

In [ ]:
# EC6 - top districts in Maharashtra by establishments
esankhyiki.get_data("EC", {
    "indicator_code": 1,
    "state": "27",       # Maharashtra
    "mode": "ranking",
    "top5opt": "2",
}, format="df")

---
## MNRE - Renewable Energy

State-wise monthly installed capacity (in MW) for solar, wind, hydro, bio, and total renewable power from the Ministry of New and Renewable Energy.

In [ ]:
# Energy types: 1=Solar, 2=Wind, 3=Hydro, 4=Bio, 5=Total
# Solar/Hydro/Bio support category_code breakdown; Wind and Total do not
esankhyiki.get_indicators("MNRE", format="df")

In [ ]:
# Filter values for Solar Power (type 1) - returns valid category_codes
metadata = esankhyiki.get_metadata("MNRE", indicator_code=1)
metadata

In [ ]:
esankhyiki.get_data("MNRE", {
    "type_of_renewable_energy_code": 1,  # Solar Power
    "state_code": 36,                    # All India
    "year": "2023",
}, format="df")

---
## Output Formats

All functions support `format="dict"` (default), `format="df"` (pandas DataFrame), or `format="csv"`.

In [ ]:
csv_str = esankhyiki.get_data("PLFS", {
    "indicator_code": 3,
    "frequency_code": 1,
    "year_type_code":1,
    "year": "2023-24",
    "state_code": 99,
    "gender_code": 3,
    "age_code": 1,
    "sector_code": 3,
}, format="csv")

print(csv_str[:600])

---
## Error Handling

In [ ]:
# Typo in dataset name - fuzzy suggestion
try:
    esankhyiki.get_indicators("plfs_data")
except InvalidDatasetError as e:
    print(e)

In [ ]:
# Missing required parameter
try:
    esankhyiki.get_metadata("PLFS", frequency_code=1)
except InvalidFilterError as e:
    print(e)

In [ ]:
# Invalid filter parameter name
try:
    esankhyiki.get_data("PLFS", {
        "indicator_code": 1,
        "frequency_code": 1,
        "typo_param": "hello",
    })
except InvalidFilterError as e:
    print(e)