# esankhyiki - Examples

Python client for India's National Statistical Office (MoSPI) data portal.
Access indicators across 22 datasets: employment, prices, GDP, health, education, environment, and more.

```bash
pip install mospi-esankhyiki[pandas]
```

In [22]:
import warnings
warnings.filterwarnings('ignore')
import esankhyiki
from esankhyiki.exceptions import InvalidDatasetError, InvalidFilterError, APIError, NoDataError

---
## Available Datasets

In [23]:
esankhyiki.list_datasets(format="df")

     dataset
0       PLFS
1        CPI
2        IIP
3        ASI
4        NAS
5        WPI
6     ENERGY
7      AISHE
8      ASUSE
9     GENDER
10      NFHS
11  ENVSTATS
12       RBI
13     NSS77
14     NSS78
15   CPIALRL
16      HCES
17       TUS
18        EC
19     NSS73
20     NSS75
21    NSS75E
22     NSS76
23    NSS76C
24     NSS79
25     NSS80
26    NSS80C
27     UDISE
28      MNRE
29       ISP

---
## NSS - 73 Unincorporated Non-Agricultural Enterprises in India (NSS 73rd Round)
The Survey includes Unincorporated Non-Agricultural Enterprises in manufacturing, trade, non-captive electricity generation & transmission and other services sector (excluding construction).

In [24]:
# Indicators  by survey_code
esankhyiki.get_indicators("NSS73", format="df")

   indicator_code                 description
0               1       Number of Enterprises
1               2           Type of Ownership
2               3                     Workers
3               4  Emolument per hired worker
4               5              GVA per worker
5               6          GVA per Enterprise

In [25]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS73", indicator_code=1)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

state_ut (37 values):
  {'state_ut_code': 37, 'description': 'All-India'}
  {'state_ut_code': 1, 'description': 'Andhra Pradesh'}
  {'state_ut_code': 31, 'description': 'A & N Islands'}
  {'state_ut_code': 2, 'description': 'Arunachal Pradesh'}
  {'state_ut_code': 3, 'description': 'Assam'}

sector (3 values):
  {'sector_code': 1, 'description': 'Rural'}
  {'sector_code': 2, 'description': 'Urban'}
  {'sector_code': 3, 'description': 'Rural+Urban'}

broad_activity_category (4 values):
  {'broad_activity_category_code': 1, 'description': 'Manufacturing'}
  {'broad_activity_category_code': 2, 'description': 'Trade'}
  {'broad_activity_category_code': 3, 'description': 'Other services'}
  {'broad_activity_category_code': 5, 'description': 'Non-captive electricity generation and transmission'}

enterprise_type (3 values):
  {'enterprise_type_code': 1, 'description': 'Own Account Enterprises'}
  {'enterprise_type_code': 2, 'description': 'Establishment'}
  {'enterprise_type_code': 3, 'description': 'All'}

activity_category (48 values):
  {'activity_category_code': 1, 'description': 'M1 - Cotton ginning, cleaning and bailing'}
  {'activity_category_code': 2, 'description': 'M2 - Manufacture of food products'}
  {'activity_category_code': 3, 'description': 'M3 - Manufacture of beverages'}
  {'activity_category_code': 4, 'description': 'M4 - Manufacture of tobacco products'}
  {'activity_category_code': 5, 'description': 'M5 - Manufacture of textiles'}

sub_indicator (0 values):

In [26]:
# get data return full data according to filter
esankhyiki.get_data("NSS73", {
    "indicator_code": 1,
    "state_ut_code": 4,
    "sector_code":1,
    "broad_activity_category_code": 1,
    "enterprise_type_code":1,
    "activity_category_code": 1,
}, format="df")

================================================================================
URL: https://api.mospi.gov.in/api/nss-73/getNss73Records?indicator_code=1&state_ut_code=4&sector_code=1&broad_activity_category_code=1&enterprise_type_code=1&activity_category_code=1
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"indicator":"Number of Enterprises","state":"Bihar","sector":"Rural","broad_activity_category":"Manufacturing","enterprise_type":"Own Account Enterprises","activity_category":"M1 - Cotton ginning, cleaning and bailing","value":"27"}],"meta_data":{"page":1,"totalRecords":1,"totalPages":1,"recordPerPage":20},"msg":"Data fetched successfully","statusCode":true}
================================================================================

,indicator,state,sector,broad_activity_category,enterprise_type,activity_category,value
0,Number of Enterprises,Bihar,Rural,Manufacturing,Own Account Enterprises,"M1 - Cotton ginning, cleaning and bailing",27

---
## NSS - 75E Household Social Consumption on Education in India (NSS 75th Round)
The surveys of social consumption relating to education, conducted by the National Statistical Office (NSO) is the primary source of data for generating various indicators on education like, level of education, attendance, incentives received by the students, expenditure on education, etc.

In [ ]:
# Indicators  by survey_code
esankhyiki.get_indicators("NSS75E", format="df")

In [ ]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS75E", indicator_code=43)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

In [ ]:
# get data return full data according to filter
esankhyiki.get_data("NSS75E", {
    "indicator_code": 43,
    "survey_code":2,
    "state_code": 4,
    "sector_code":1,
    "gender_code": 1,
}, format="df")

---
## NSS - 75 Household Social Consumption on Health in India (NSS 75th Round)
The surveys of social consumption relating to Health, conducted by the National Statistical Office (NSO) is the primary source of data for generating various indicators.

In [50]:
# Indicators  by survey_code
esankhyiki.get_indicators("NSS75", format="df")

,indicator_code,label,survey_code
0,1,Hospitalisation cases (excluding childbirth) p...,1
1,2,Hospitalisation cases (excluding childbirth) p...,1
2,3,Cases of hospitalisation (excluding childbirth...,1
3,4,Percentage distribution of hospitalised cases ...,1
4,5,Percentage distribution of hospitalised cases ...,1
5,6,Percentage distribution of hospitalised cases ...,1
6,7,Percentage distribution of hospitalisation cas...,1
7,8,Percentage distribution of hospitalisation cas...,1
8,9,Percentage distribution of hospitalisation cas...,1
9,10,Average medical expenditure for treatment per ...,1
10,11,Average total medical expenditure per hospital...,1
11,12,Average medical expenditure for treatment per ...,1
12,13,Average medical expenditure and non-medical ex...,1
13,14,Average medical expenditure and non-medical ex...,1
14,15,Average medical expenditure (Rs.) per hospital...,1
15,16,Average out-of-pocket medical expenditure (OOP...,1
16,17,Average out-of-pocket medical expenditure (OOP...,1
17,18,Number per 1000 persons reporting ailments (PA...,1
18,19,Number of ailments reported Per 100000 persons...,1
19,20,Number of ailments of each broad ailment categ...,1
20,21,Percentage distribution of spells of ailment o...,1
21,22,"Number of persons per 1,00,000 reporting onset...",1
22,23,Average medical expenditure and non-medical ex...,1
23,24,Average medical expenditure and non-medical ex...,1
24,25,Average medical expenditure for (non-hospitali...,1
25,26,Average medical expenditure for (non-hospitali...,1
26,27,Average medical expenditure for (non-hospitali...,1
27,28,Average medical expenditure for (non-hospitali...,1
28,29,Average out-of-pocket medical expenditure for ...,1
29,30,Percentage distribution of aged persons by sta...,1
30,31,Percentage distribution of aged persons of eac...,1
31,32,Percentage distribution of aged persons of eac...,1
32,33,Percentage of children (0 – 5 years) receiving...,1
33,34,Percentage distribution of cases of hospitalis...,1
34,35,Percentage distribution of cases of hospitalis...,1
35,36,Percentage distribution of cases of hospitalis...,1
36,37,Average total expenditure per childbirth (excl...,1
37,38,Average total expenditure per childbirth (exc...,1
38,39,Average medical and non-medical expenditure (R...,1
39,40,Average medical and non-medical expenditure (R...,1
40,41,Average out-of-pocket medical expenditure (OOP...,1
41,42,Average out-of-pocket medical expenditure (OOP...,1

In [51]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS75E", indicator_code=30)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

state (37 values):
  {'id': 39, 'label': 'All India'}
  {'id': 31, 'label': 'Andaman & N.Islands'}
  {'id': 1, 'label': 'Andhra Pradesh'}
  {'id': 2, 'label': 'Arunachal Pradesh'}
  {'id': 3, 'label': 'Assam'}

sector (3 values):
  {'id': 1, 'label': 'Rural'}
  {'id': 2, 'label': 'Urban'}
  {'id': 4, 'label': 'All'}

gender (3 values):
  {'id': 1, 'label': 'Male '}
  {'id': 2, 'label': 'Female'}
  {'id': 5, 'label': 'Person'}

In [52]:
# get data return full data according to filter
esankhyiki.get_data("NSS75E", {
    "indicator_code": 30,
    "survey_code":1,
    "state_code": 4,
    "sector_code":1,
    "gender_code": 1,
}, format="df")

================================================================================
URL: https://api.mospi.gov.in/api/nss-75/getNss75Records?indicator_code=30&survey_code=1&state_code=4&sector_code=1&gender_code=1
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"indicator":"Percentage distribution of aged persons by state of economic independence for each State/UT","state":"Bihar","sector":"Rural","gender":"Male ","value":"49"},{"indicator":"Percentage distribution of aged persons by state of economic independence for each State/UT","state":"Bihar","sector":"Rural","gender":"Male ","value":"27"},{"indicator":"Percentage distribution of aged persons by state of economic independence for each State/UT","state":"Bihar","sector":"Rural","gender":"Male ","value":"23"},{"indicator":"Percentage distribution of aged persons by state of economic independence for each State/UT","state":"Bihar","sector":"Rural","gender":"Male ","value":"100"}],"meta_data":{"page":1,"totalRecords":4,"totalPages":1,"recordPerPage":10},"msg":"Data fetched successfully","statusCode":true}
================================================================================

,indicator,state,sector,gender,value
0,Percentage distribution of aged persons by sta...,Bihar,Rural,Male,49
1,Percentage distribution of aged persons by sta...,Bihar,Rural,Male,27
2,Percentage distribution of aged persons by sta...,Bihar,Rural,Male,23
3,Percentage distribution of aged persons by sta...,Bihar,Rural,Male,100

---
## NSS - 76 Drinking Water, Sanitation, Hygiene and Housing Condition in India (NSS 76th Round)
The objective of NSS 76th round from July to December 2018, is to examine and study different aspects of living conditions necessary for decent and healthy living of the household members by developing suitable indicators based on the information collected through the survey.

In [53]:
# Indicators  by survey_code
esankhyiki.get_indicators("NSS76", format="df")

,indicator_code,label,survey_code
0,23,Average floor area (0.00 sq. mtr.) of the dwel...,2
1,24,Average number of living rooms of the househol...,2
2,22,Average plinth level of the house (0.00 mtr.) ...,2
3,19,Percentage distribution of households by metho...,2
4,15,Percentage distribution of households by suppl...,2
5,26,Percentage distribution of households living i...,2
6,14,Percentage distribution of households not gett...,2
7,21,Percentage of households having bathroom and l...,2
8,16,Percentage of households having improved sourc...,2
9,25,Percentage of households (living in a house) h...,2
10,18,Percentage of households which covered the mai...,2
11,20,Percentage of persons regularly used improved ...,2

In [56]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS76", indicator_code=16)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

state (39 values):
  {'id': 1, 'label': 'Andhra Pradesh'}
  {'id': 2, 'label': 'Arunachal Pradesh'}
  {'id': 3, 'label': 'Assam'}
  {'id': 4, 'label': 'Bihar'}
  {'id': 5, 'label': 'Chhattisgarh'}

sector (3 values):
  {'id': 1, 'label': 'Rural'}
  {'id': 2, 'label': 'Urban'}
  {'id': 3, 'label': 'Rural + Urban'}

quintile_class (6 values):
  {'id': 1, 'label': '00-20'}
  {'id': 2, 'label': '20-40'}
  {'id': 3, 'label': '40-60'}
  {'id': 4, 'label': '60-80'}
  {'id': 5, 'label': '80-100'}

households_percentage (6 values):
  {'id': 1, 'label': 'Households having access to  improved source of drinking water'}
  {'id': 2, 'label': 'Households having access to  improved source of drinking water located in the household premises'}
  {'id': 3, 'label': 'Households having exclusive access to improved source of drinking water located in the household premises'}
  {'id': 4, 'label': 'Households having access to improved source of drinking water located in the household premises which is sufficiently available throughout the year'}
  {'id': 5, 'label': 'Households having exclusive access to improved source of drinking water located in the household premises which is sufficiently available throughout the year'}

In [57]:
# get data return full data according to filter
esankhyiki.get_data("NSS76", {
    "indicator_code": 16,
    "survey_code":2,
    "state_code": 4,
    "sector_code":1,
    "quintile_class_code": 1,
    "households_percentage_code": 1,
}, format="df")

================================================================================
URL: https://api.mospi.gov.in/api/nss-76/getNss76Records?indicator_code=16&survey_code=2&state_code=4&sector_code=1&quintile_class_code=1&households_percentage_code=1
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"indicator":"Percentage of households having improved source of drinking water","state":"Bihar","sector":"Rural","quintile_class":"00-20","households_percentage":"Households having access to  improved source of drinking water","value":"99.7"}],"meta_data":{"page":1,"totalRecords":1,"totalPages":1,"recordPerPage":10},"msg":"Data fetched successfully","statusCode":true}
================================================================================

,indicator,state,sector,quintile_class,households_percentage,value
0,Percentage of households having improved sourc...,Bihar,Rural,00-20,Households having access to improved source o...,99.7

---
## NSS - 76C Persons with Disabilities in India (NSS 76th Round)
In NSS 76th round survey for classification of disabilities, all the specified disabilities stated in The Right of Persons with Disabilities Act, 2016 have been considered.

In [59]:
# Indicators  by survey_code
esankhyiki.get_indicators("NSS76C", format="df")

,indicator_code,label,survey_code
0,3,Literacy rate (in per cent) of persons of age ...,1
1,11,Percentage distribution of persons with disabi...,1
2,13,Percentage distribution of persons with disabi...,1
3,4,Percentage of persons of age 15 years and abov...,1
4,2,Percentage of persons with broad type of disab...,1
5,1,Percentage of persons with disability,1
6,7,Percentage of persons with disability by statu...,1
7,6,Percentage of persons with disability having d...,1
8,5,Percentage of persons with disability having d...,1
9,12,Percentage of persons with disability who used...,1
10,10,Percentage of persons with hearing disability ...,1
11,8,Percentage of persons with locomotor disabilit...,1
12,9,Percentage of persons with visual disability w...,1

In [64]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS76C", indicator_code=12)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

state (37 values):
  {'id': 1, 'label': 'Andhra Pradesh'}
  {'id': 2, 'label': 'Arunachal Pradesh'}
  {'id': 3, 'label': 'Assam'}
  {'id': 4, 'label': 'Bihar'}
  {'id': 5, 'label': 'Chhattisgarh'}

gender (3 values):
  {'id': 1, 'label': 'Male'}
  {'id': 2, 'label': 'Female'}
  {'id': 3, 'label': 'Person'}

sector (3 values):
  {'id': 1, 'label': 'Rural'}
  {'id': 2, 'label': 'Urban'}
  {'id': 3, 'label': 'Rural + Urban'}

use_of_public_transport (4 values):
  {'id': 1, 'label': 'Used public transport'}
  {'id': 2, 'label': 'Used public transport and faced difficulties'}
  {'id': 3, 'label': 'Accessed public building'}
  {'id': 4, 'label': 'Accessed public building and faced difficulties'}

In [66]:
# get data return full data according to filter
esankhyiki.get_data("NSS76C", {
    "indicator_code": 12,
    "survey_code":1,
    "state_code": 4,
    "sector_code":1,
    "gender_code": 1,
    "use_of_public_transport_code": 1,
}, format="df")

================================================================================
URL: https://api.mospi.gov.in/api/nss-76/getNss76Records?indicator_code=12&survey_code=1&state_code=4&sector_code=1&gender_code=1&use_of_public_transport_code=1
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"indicator":"Percentage of persons with disability who used/ accessed public transport during last 365 days, accessed public building during last 365 days and problems faced in accessing/using publictransport/public building","state":"Bihar","gender":"Male","sector":"Rural","use_of_public_transport":null,"value":"48.2"}],"meta_data":{"page":1,"totalRecords":1,"totalPages":1,"recordPerPage":10},"msg":"Data fetched successfully","statusCode":true}
================================================================================

,indicator,state,gender,sector,use_of_public_transport,value
0,Percentage of persons with disability who used...,Bihar,Male,Rural,None,48.2

---
## NSS - 80 Comprehensive Modular Survey: Telecom (CMST) (NSS 80th Round)
 Comprehensive Modular Survey: Telecom (CMST) from January to March 2025 collected data on various aspects of mobile and internet usage at both the household and individual levels. Additionally, information on selected ICT skills was also captured.

In [67]:
# Indicators  by survey_code
esankhyiki.get_indicators("NSS80", format="df")

    indicator_code                                               desc
0               20  Percentage of households made online purchases...
1               17  Percentage of households possessing landline, ...
2               18  Percentage of households with internet facilit...
3               19  Percentage of households without internet faci...
4               13  Percentage of persons able to complain about c...
5               12  Percentage of persons able to create electroni...
6               16  Percentage of persons who are able to perform ...
7               14  Percentage of persons who are able to send or ...
8                6  Percentage of persons who are able to use inte...
9               11  Percentage of persons who created an electroni...
10               3  Percentage of persons who own a mobile phone a...
11               4         Percentage of persons who own mobile phone
12              15  Percentage of persons who reported the ability...
13               9  Percentage of persons who sent message (e.g., ...
14              10  Percentage of persons who used copy and paste ...
15               5  Percentage of persons who used internet, at le...
16               7  Percentage of persons who used internet at lea...
17               8  Percentage of persons who used internet at lea...
18               1  Percentage of persons who used mobile phone du...
19               2  Percentage of persons who used mobile phone du...

In [70]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS80", indicator_code=12)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

state (37 values):
  {'desc': 'All-India', 'state_code': 37}
  {'desc': 'Andhra Pradesh', 'state_code': 1}
  {'desc': 'A & N Islands', 'state_code': 30}
  {'desc': 'Arunachal Pradesh', 'state_code': 2}
  {'desc': 'Assam', 'state_code': 3}

gender (3 values):
  {'desc': 'Male', 'gender_code': 1}
  {'desc': 'Female', 'gender_code': 2}
  {'desc': 'Person', 'gender_code': 3}

sector (3 values):
  {'desc': 'Rural', 'sector_code': 1}
  {'desc': 'Urban', 'sector_code': 2}
  {'desc': 'All', 'sector_code': 3}

agegroup (3 values):
  {'desc': '15-24 Years', 'agegroup_code': 1}
  {'desc': '15-29 Years', 'agegroup_code': 2}
  {'desc': '15 Years and above', 'agegroup_code': 3}

In [72]:
# get data return full data according to filter
esankhyiki.get_data("NSS80", {
    "indicator_code": 12,
    "survey_code":1,
    "state_code": 4,
    "sector_code":1,
    "gender_code": 1,
    "agegroup_code": 1,
}, format="df")

================================================================================
URL: https://api.mospi.gov.in/api/nss-80/getNSS80Records?indicator_code=12&survey_code=1&state_code=4&sector_code=1&gender_code=1&agegroup_code=1
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"indicator":"Percentage of persons able to create electronic documents with word processing software","state":"Bihar","agegroup":"15-24 Years","gender":"Male","sector":"Rural","value":"12.3"}],"meta_data":{"page":1,"totalRecords":1,"totalPages":1,"recordPerPage":10},"msg":"Data fetched successfully","statusCode":true}
================================================================================

,indicator,state,agegroup,gender,sector,value
0,Percentage of persons able to create electroni...,Bihar,15-24 Years,Male,Rural,12.3

---
## NSS - 80C Comprehensive Modular Survey: Education (CMSE) (NSS 80th Round)
 Comprehensive Modular Survey: Education (CMSE) from April to June 2025 primarily collected expenditure-related information incurred by the student households enrolled in school education.

In [73]:
# Indicators  by survey_code
esankhyiki.get_indicators("NSS80C", format="df")

    indicator_code                                               desc
0               40  Average expenditure (₹) on private coaching pe...
1               39  Average expenditure (₹) on private coaching pe...
2               37  Average expenditure (₹) per reported student i...
3               35  Average expenditure (₹) per reported student o...
4               34  Average expenditure (₹) per reported student o...
5               36  Average expenditure (₹) per reported student o...
6               33  Average expenditure (₹) per student on school ...
7               30  Average expenditure (₹) per student on school ...
8               31  Average expenditure (₹) per student on school ...
9               32  Average expenditure (₹) per student on school ...
10              25  Distribution of students currently enrolled in...
11              24  Distribution of students currently enrolled in...
12              23  Distribution of students enrolled in school ed...
13              42  Percentage of households reporting erstwhile m...
14              41  Percentage of students reported a single sourc...
15              28  Percentage of students reported expenditure on...
16              29  Percentage of students reported expenditure on...
17              38  Percentage of students who were taking/had tak...

In [75]:
# Filter by indicator_code
metadata = esankhyiki.get_metadata("NSS80C", indicator_code=29)

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values[:5]:
        print(f"  {v}")

state (37 values):
  {'desc': 'All-India', 'state_code': 37}
  {'desc': 'Andhra Pradesh', 'state_code': 1}
  {'desc': 'A & N Islands', 'state_code': 30}
  {'desc': 'Arunachal Pradesh', 'state_code': 2}
  {'desc': 'Assam', 'state_code': 3}

gender (3 values):
  {'desc': 'Male', 'gender_code': 1}
  {'desc': 'Female', 'gender_code': 2}
  {'desc': 'Person', 'gender_code': 3}

sector (3 values):
  {'desc': 'Rural', 'sector_code': 1}
  {'desc': 'Urban', 'sector_code': 2}
  {'desc': 'All', 'sector_code': 3}

type_of_school (6 values):
  {'desc': 'Government', 'type_of_school_code': 1}
  {'desc': 'Private Aided', 'type_of_school_code': 2}
  {'desc': 'Private Unaided (Recognised)', 'type_of_school_code': 3}
  {'desc': 'Others', 'type_of_school_code': 4}
  {'desc': 'All Non-Government', 'type_of_school_code': 5}

In [78]:
# get data return full data according to filter
esankhyiki.get_data("NSS80C", {
    "indicator_code": 29,
    "survey_code":2,
    "state_code": 4,
    "sector_code":1,
    "gender_code": 1,
    "type_of_school_code": 1,
}, format="df")

================================================================================
URL: https://api.mospi.gov.in/api/nss-80/getNSS80Records?indicator_code=29&survey_code=2&state_code=4&sector_code=1&gender_code=1&type_of_school_code=1
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"indicator":"Percentage of students reported expenditure on course fees by type of school","state":"Bihar","gender":"Male","type_of_school":"Government","sector":"Rural","value":"25.2"}],"meta_data":{"page":1,"totalRecords":1,"totalPages":1,"recordPerPage":10},"msg":"Data fetched successfully","statusCode":true}
================================================================================

,indicator,state,gender,type_of_school,sector,value
0,Percentage of students reported expenditure on...,Bihar,Male,Government,Rural,25.2

## ISP - Index of Services Production - Trial Series

Provides experimental estimates of service sector production across selected service industries.
Use `get_indicators` to view available indicator codes and `get_metadata` to retrieve valid filter values for a selected indicator.

In [12]:
# Indicators  by survey_code
esankhyiki.get_indicators("ISP", format="df")

   frequency_code       desc
0               1  Yearly111
1               2    Monthly

In [17]:
metadata = esankhyiki.get_metadata("ISP", frequency_code=1)[0]

for key, values in metadata.items():
    print(f"\n{key} ({len(values)} values):")
    for v in values:
        print(v)

frequency (2 values):
{'frequency_code': 1, 'description': 'Yearly'}
{'frequency_code': 2, 'description': 'Monthly'}

year (1 values):
{'year': '2025-26'}

broad_sub_sector (19 values):
{'broad_sub_sector_code': 1, 'description': 'Wholesale Trade'}
{'broad_sub_sector_code': 2, 'description': 'Retail Trade'}
{'broad_sub_sector_code': 3, 'description': 'Repair Services'}
{'broad_sub_sector_code': 4, 'description': 'Accommodation and food '}
{'broad_sub_sector_code': 5, 'description': 'Railway Transport'}
{'broad_sub_sector_code': 6, 'description': 'Road Transport'}
{'broad_sub_sector_code': 7, 'description': 'Water Transport'}
{'broad_sub_sector_code': 8, 'description': 'Air Transport'}
{'broad_sub_sector_code': 9, 'description': 'Warehousing and support activities for transportation'}
{'broad_sub_sector_code': 10, 'description': 'Postal and Courier '}
{'broad_sub_sector_code': 11, 'description': 'Telecommunication'}
{'broad_sub_sector_code': 12, 'description': 'Information and Broadcasting'}
{'broad_sub_sector_code': 13, 'description': 'Banking '}
{'broad_sub_sector_code': 14, 'description': 'Insurance '}
{'broad_sub_sector_code': 15, 'description': 'Real Estate'}
{'broad_sub_sector_code': 16, 'description': 'IT & computer related services'}
{'broad_sub_sector_code': 17, 'description': 'Professional, scientific & technical services including R & D'}
{'broad_sub_sector_code': 18, 'description': 'Administrative and support services'}
{'broad_sub_sector_code': 19, 'description': 'Arts, Entertainment  and Recreation '}

In [21]:
esankhyiki.get_data(
    "ISP",
    {
        "frequency_code": 1,
        "year": "2025-26",
        "broad_sub_sector_code": 3,
    },
    format="df",
)

================================================================================
URL: https://api.mospi.gov.in/api/isp/getISPRecords?frequency_code=1&year=2025-26&broad_sub_sector_code=3
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"base_year":"2024-25","year":"2025-26","frequency":"Yearly","broad_sub_sector":"Repair Services","index":"125.1","growth_rate":"25.1"}],"meta_data":{"page":1,"totalRecords":1,"totalPages":1,"recordPerPage":10},"msg":"Data fetched successfully","statusCode":true}
================================================================================

  base_year     year frequency broad_sub_sector  index growth_rate
0   2024-25  2025-26    Yearly  Repair Services  125.1        25.1

---
## PLFS - Periodic Labour Force Survey

Covers labour force participation, unemployment, worker population ratio, wages.
Use `get_indicators` to see what indicator codes are available, `get_metadata` to see valid filter values for a given indicator.

In [ ]:
# Indicators grouped by frequency_code
indicators = esankhyiki.get_indicators("PLFS")
for group, items in indicators["indicators_by_frequency"].items():
    print(f"\n{group}:")
    for item in items:
        print(f"  {item['indicator_code']}: {item.get('indicator_name', item.get('description', ''))}")

In [ ]:
# Valid filter values for Unemployment Rate (indicator_code=3), Annual (frequency_code=1)
metadata = esankhyiki.get_metadata("PLFS", indicator_code=3, frequency_code=1, year_type_code=1)
for key, values in metadata["filter_values"]["data"].items():
    print(f"\n{key}:")
    for v in values[:4]:
        print(f"  {v}")

In [ ]:
# Unemployment Rate - All India, all years, both sectors
esankhyiki.get_data("PLFS", {
    "indicator_code": 3,
    "frequency_code": 1,
    "year_type_code":1,
    "state_code": 99,     # 99 = All India
    "gender_code": 3,     # 3 = Person
    "age_code": 1,        # 1 = 15 years and above
    "sector_code": 3,     # 3 = rural + urban
}, format="df")

---
## CPI - Consumer Price Index

Multiple base years (2010, 2012, 2024) and two levels: Group and Item.

In [ ]:
# Available base years, levels, and series
esankhyiki.get_indicators("CPI", format="df")

In [ ]:
# Filter values for base_year=2012, Group level
metadata = esankhyiki.get_metadata("CPI", base_year="2012", level="Group", series="Current", format="df")
metadata

In [ ]:
# CPI Group index, base year 2012, year 2024
esankhyiki.get_data("CPI", {
    "base_year": "2012",
    "series": "Current",
    "year": "2024",
}, format="df")

---
## NAS - National Accounts Statistics (GDP)

Annual and quarterly GDP, GVA, consumption, capital formation by industry and institutional sector.

In [ ]:
esankhyiki.get_indicators("NAS", format="df")

In [ ]:
# Filter values for GVA by industry (indicator_code=1), base year 2022-23
metadata = esankhyiki.get_metadata("NAS", indicator_code=1, base_year="2022-23", series="Current", frequency_code=1)
for key, values in metadata.items():
    if isinstance(values, list):
        print(f"{key}: {values[:3]}")

In [ ]:
# GVA by industry, current prices, latest estimates
esankhyiki.get_data("NAS", {
    "indicator_code": 1,
    "base_year": "2022-23",
    "series": "Current",
    "frequency_code": 1,
    "year": "2024-25",
}, format="df")

---
## IIP - Index of Industrial Production

Monthly and annual industrial output across manufacturing, mining, and electricity sectors.

In [ ]:
# Available categories and years for IIP annual
metadata = esankhyiki.get_metadata("IIP", base_year="2011-12", frequency="Annually")
metadata

In [ ]:
# IIP annual, 2023-24
esankhyiki.get_data("IIP", {
    "base_year": "2011-12",
    "financial_year": "2023-24",
}, format="df")

---
## GENDER - Gender Statistics

147 indicators covering demographics, health, education, labour, financial inclusion, and crimes against women.

In [ ]:
indicators = esankhyiki.get_indicators("GENDER")
print(f"Total indicators: {len(indicators)}\n")
for i in indicators[:10]:
    print(f"  {i['indicator_code']}: {i['description']}")

In [ ]:
# Sex ratio (indicator_code=2)
esankhyiki.get_data("GENDER", {"indicator_code": 2}, format="df")

---
## ENVSTATS - Environment Statistics

124 indicators covering climate, water, forests, biodiversity, pollution, and natural disasters.

In [ ]:
indicators = esankhyiki.get_indicators("ENVSTATS")
print(f"Total indicators: {len(indicators)}\n")
for i in indicators[:10]:
    print(f"  {i['indicator_code']}: {i.get('description', i.get('label', ''))}")

In [ ]:
# Mean temperature trend (indicator_code=1)
esankhyiki.get_data("ENVSTATS", {"indicator_code": 1}, format="df")

---
## RBI - Foreign Trade and Exchange Rates

39 indicators on balance of payments, forex reserves, exchange rates (155 currencies), NRI deposits.

In [22]:
indicators = esankhyiki.get_indicators("RBI")
for i in indicators:
    print(f"  {i['indicator_code']}: {i['label']}")

  22: Balance of Payments ‑ Indicators
  24: Broad Commodity Composition of India's Merchandise Trade ‑ Oil and Non oil Exports and Imports ‑ Rupees
  42: Broad Commodity Composition of India’s Merchandise Trade - Oil and Non-Oil Exports and Imports - US Dollar
  1: Direction of Foreign Trade ‑ Rupees
  11: Direction of Foreign Trade ‑ US Dollars
  32: Exchange Rate of the Indian Rupee Vis‑a‑Vis the SDR, US Dollar, Pound Sterling, D.M./Euro and Japanese Yen (Calendar Year ‑ Annual Average)
  31: Exchange Rate of the Indian Rupee Vis‑A‑Vis the SDR, US Dollar, Pound Sterling, D.M./Euro and Japanese Yen (Financial Year ‑ Annual Average and End‑Year Rates)
  35: Exchange Rate of the Indian Rupee vis-à-vis the SDR, US Dollar, Pound Sterling, Euro and Japanese Yen (High and Low During the Month)
  33: Exchange Rate of the Indian Rupee vis-à-vis the SDR, US Dollar, Pound Sterling, Euro and Japanese Yen (Monthly Average and end-Month Rates)
  43: EXPORTS OF MAJOR COMMODITIES - RUPEES
  44: EXPORTS OF MAJOR COMMODITIES - US Dollars
  2: Exports of Select Commodities to Principal Countries ‑ Rupees
  20: Exports of Select Commodities to Principal Countries ‑ US Dollars
  27: External Debt of India ‑ Quarterly
  48: Foreign Exchange Reserve Annual
  47:  Foreign Exchange Reserve Monthly
  29: Forex Rates ‑ Month‑High / Month‑Low
  34: Forward Premia (Inter‑Bank) (Monthly Average)
  45: Imports of Major Commodities - Rupees
  46: Imports of Major Commodities - US Dollars
  26: India's External Debt ‑ Rupees (End‑March)
  25: India's External Debt ‑ US Dollars (End‑March)
  13: India's Foreign Trade – Rupees
  17: India's Foreign Trade – Rupees-Annual
  12: India's Foreign Trade ‑ US Dollars
  16: India's Foreign Trade ‑ US Dollars - Annual
  10: India’s Overall Balance of Payments – Quarterly – Rupees
  4: India's Overall Balance of Payments ‑ Quarterly ‑ US Dollars
  6: India's Overall Balance of Payments – Rupees
  5: India's Overall Balance of Payments ‑ US Dollars
  14: Invisibles by Category of Transactions – Rupees
  9: Invisibles by Category of Transactions – US Dollars
  7: Key Components of India's Balance of Payments – Rupees
  8: Key Components of India's Balance of Payments ‑ US Dollars
  37: Monthly Average Exchange Rate (155 Currencies)
  36: Monthly Average Exchange Rates (EURO, GBP, JPY, USD)
  40: NRI Deposits - Outstandings and Inflows(+) / Outflows(-)
  28: Sale/ Purchase of U.S. Dollar by the RBI
  30: Turnover in Foreign Exchange Market

In [23]:
# Get valid sub_indicator_codes for Balance of Payments (indicator_code=22)
metadata = esankhyiki.get_metadata("RBI", sub_indicator_code=22)
metadata

[{'sub_indicator_code': 22,
  'label': 'Balance of Payments ‑ Indicators',
  'dimensions': {'year': [{'id': '2024-25', 'label': '2024-25'},
    {'id': '2023-24', 'label': '2023-24'},
    {'id': '2022-23', 'label': '2022-23'},
    {'id': '2021-22', 'label': '2021-22'},
    {'id': '2020-21', 'label': '2020-21'},
    {'id': '2019-20', 'label': '2019-20'},
    {'id': '2018-19', 'label': '2018-19'},
    {'id': '2017-18', 'label': '2017-18'},
    {'id': '2016-17', 'label': '2016-17'},
    {'id': '2015-16', 'label': '2015-16'},
    {'id': '2014-15', 'label': '2014-15'},
    {'id': '2013-14', 'label': '2013-14'},
    {'id': '2012-13', 'label': '2012-13'},
    {'id': '2011-12', 'label': '2011-12'},
    {'id': '2010-11', 'label': '2010-11'},
    {'id': '2009-10', 'label': '2009-10'},
    {'id': '2008-09', 'label': '2008-09'},
    {'id': '2007-08', 'label': '2007-08'},
    {'id': '2006-07', 'label': '2006-07'},
    {'id': '2005-06', 'label': '2005-06'},
    {'id': '2004-05', 'label': '2004-05'},
    {'id': '2003-04', 'label': '2003-04'},
    {'id': '2002-03', 'label': '2002-03'},
    {'id': '2001-02', 'label': '2001-02'},
    {'id': '2000-01', 'label': '2000-01'},
    {'id': '1999-00', 'label': '1999-00'},
    {'id': '1998-99', 'label': '1998-99'},
    {'id': '1997-98', 'label': '1997-98'},
    {'id': '1996-97', 'label': '1996-97'},
    {'id': '1995-96', 'label': '1995-96'},
    {'id': '1994-95', 'label': '1994-95'},
    {'id': '1993-94', 'label': '1993-94'},
    {'id': '1992-93', 'label': '1992-93'},
    {'id': '1991-92', 'label': '1991-92'},
    {'id': '1990-91', 'label': '1990-91'},
    {'id': '1989-90', 'label': '1989-90'},
    {'id': '1988-89', 'label': '1988-89'},
    {'id': '1987-88', 'label': '1987-88'},
    {'id': '1986-87', 'label': '1986-87'},
    {'id': '1985-86', 'label': '1985-86'},
    {'id': '1984-85', 'label': '1984-85'},
    {'id': '1983-84', 'label': '1983-84'},
    {'id': '1982-83', 'label': '1982-83'},
    {'id': '1981-82', 'label': '1981-82'},
    {'id': '1980-81', 'label': '1980-81'},
    {'id': '1979-80', 'label': '1979-80'},
    {'id': '1978-79', 'label': '1978-79'},
    {'id': '1977-78', 'label': '1977-78'},
    {'id': '1976-77', 'label': '1976-77'},
    {'id': '1975-76', 'label': '1975-76'},
    {'id': '1974-75', 'label': '1974-75'},
    {'id': '1973-74', 'label': '1973-74'},
    {'id': '1972-73', 'label': '1972-73'},
    {'id': '1971-72', 'label': '1971-72'},
    {'id': '1970-71', 'label': '1970-71'}],
   'balance_of_payments': [{'id': 1,
     'label': 'Capital account',
     'children': {'trade_category': [{'id': 5,
        'label': 'Foreign Investment/ Exports',
        'children': {}},
       {'id': 6, 'label': 'Foreign Investment/ GDP', 'children': {}}]}},
    {'id': 2,
     'label': 'Current account',
     'children': {'trade_category': [{'id': 1,
        'label': 'CAD/ GDP',
        'children': {}},
       {'id': 2,
        'label': 'Current Receipts/ Current Payments',
        'children': {}},
       {'id': 3, 'label': 'Current Receipts/ GDP', 'children': {}}]}},
    {'id': 3,
     'label': 'Invisibles',
     'children': {'trade_category': [{'id': 8,
        'label': 'Net/ GDP',
        'children': {}},
       {'id': 9, 'label': 'Payments/GDP', 'children': {}},
       {'id': 10, 'label': 'Receipts/GDP', 'children': {}}]}},
    {'id': 4,
     'label': 'Trade',
     'children': {'trade_category': [{'id': 4,
        'label': 'Exports/ GDP',
        'children': {}},
       {'id': 7, 'label': 'Imports/ GDP', 'children': {}}]}},
    {'id': 5,
     'label': 'Import cover of Reserves (in months)',
     'children': {'trade_category': []}}]}}]

In [ ]:
# Balance of Payments
esankhyiki.get_data("RBI", {"indicator_code": 22}, format="df")

---
## EC - Economic Census

District-level establishment and worker counts across three census editions (EC4/EC5/EC6).

In [ ]:
esankhyiki.get_indicators("EC", format="df")

In [ ]:
# EC6 (2013-14) - available states and filter options
metadata = esankhyiki.get_metadata("EC", indicator_code=1)
metadata

In [ ]:
# EC6 - top districts in Maharashtra by establishments
esankhyiki.get_data("EC", {
    "indicator_code": 1,
    "state": "27",       # Maharashtra
    "mode": "ranking",
    "top5opt": "2",
}, format="df")

---
## MNRE - Renewable Energy

State-wise monthly installed capacity (in MW) for solar, wind, hydro, bio, and total renewable power from the Ministry of New and Renewable Energy.

In [2]:
# Energy types: 1=Solar, 2=Wind, 3=Hydro, 4=Bio, 5=Total
# Solar/Hydro/Bio support category_code breakdown; Wind and Total do not
esankhyiki.get_indicators("MNRE", format="df")

   type_of_renewable_energy_code        label
0                              1  Solar Power
1                              2   Wind Power
2                              3  Hydro Power
3                              4    Bio Power
4                              5  Total Power

In [27]:
# Filter values for Solar Power (type 1) - returns valid category_codes
metadata = esankhyiki.get_metadata("MNRE", indicator_code=1)
metadata

[{'year': [{'year': 2026},
   {'year': 2025},
   {'year': 2024},
   {'year': 2023},
   {'year': 2022},
   {'year': 2021},
   {'year': 2020}],
  'month': [{'month_code': 1, 'label': 'January'},
   {'month_code': 2, 'label': 'February'},
   {'month_code': 3, 'label': 'March'},
   {'month_code': 4, 'label': 'April'},
   {'month_code': 5, 'label': 'May'},
   {'month_code': 6, 'label': 'June'},
   {'month_code': 7, 'label': 'July'},
   {'month_code': 8, 'label': 'August'},
   {'month_code': 9, 'label': 'September'},
   {'month_code': 10, 'label': 'October'},
   {'month_code': 11, 'label': 'November'},
   {'month_code': 12, 'label': 'December'}],
  'state': [{'state_code': 36, 'label': 'All India'},
   {'state_code': 39, 'label': 'Andaman and Nicobar Islands'},
   {'state_code': 1, 'label': 'Andhra Pradesh'},
   {'state_code': 2, 'label': 'Arunachal Pradesh'},
   {'state_code': 3, 'label': 'Assam'},
   {'state_code': 4, 'label': 'Bihar'},
   {'state_code': 30, 'label': 'Chandigarh'},
   {'state_code': 5, 'label': 'Chhattisgarh'},
   {'state_code': 37, 'label': 'Dadar and Nagar Haveli'},
   {'state_code': 31, 'label': 'Dadra  Nagar Haveli & Daman and Diu'},
   {'state_code': 38, 'label': 'Daman and Diu'},
   {'state_code': 6, 'label': 'Delhi'},
   {'state_code': 7, 'label': 'Goa'},
   {'state_code': 8, 'label': 'Gujarat'},
   {'state_code': 9, 'label': 'Haryana'},
   {'state_code': 10, 'label': 'Himachal Pradesh'},
   {'state_code': 32, 'label': 'Jammu and Kashmir'},
   {'state_code': 11, 'label': 'Jharkhand'},
   {'state_code': 12, 'label': 'Karnataka'},
   {'state_code': 13, 'label': 'Kerala'},
   {'state_code': 33, 'label': 'Ladakh'},
   {'state_code': 34, 'label': 'Lakshadweep'},
   {'state_code': 14, 'label': 'Madhya Pradesh'},
   {'state_code': 15, 'label': 'Maharashtra'},
   {'state_code': 16, 'label': 'Manipur'},
   {'state_code': 17, 'label': 'Meghalaya'},
   {'state_code': 18, 'label': 'Mizoram'},
   {'state_code': 19, 'label': 'Nagaland'},
   {'state_code': 20, 'label': 'Odisha'},
   {'state_code': 40, 'label': 'Others'},
   {'state_code': 35, 'label': 'Puducherry'},
   {'state_code': 21, 'label': 'Punjab'},
   {'state_code': 22, 'label': 'Rajasthan'},
   {'state_code': 23, 'label': 'Sikkim'},
   {'state_code': 24, 'label': 'Tamil Nadu'},
   {'state_code': 25, 'label': 'Telangana'},
   {'state_code': 26, 'label': 'Tripura'},
   {'state_code': 28, 'label': 'Uttarakhand'},
   {'state_code': 27, 'label': 'Uttar Pradesh'},
   {'state_code': 29, 'label': 'West Bengal'}],
  'category': [{'category_code': 1,
    'label': 'Ground Mounted Solar Power',
    'type_of_renewable_energy_code': 1},
   {'category_code': 2,
    'label': 'Rooftop Solar Power',
    'type_of_renewable_energy_code': 1},
   {'category_code': 3,
    'label': ' Hybrid Solar Component',
    'type_of_renewable_energy_code': 1},
   {'category_code': 4,
    'label': 'Off-Grid Solar Power/KUSUM',
    'type_of_renewable_energy_code': 1},
   {'category_code': 5,
    'label': 'Solar Power Total',
    'type_of_renewable_energy_code': 1}]}]

In [28]:
esankhyiki.get_data("MNRE", {
    "type_of_renewable_energy_code": 1,  # Solar Power
    "state_code": 36,                    # All India
    "year": "2023",
}, format="df")

================================================================================
URL: https://api.mospi.gov.in/api/mnre/getDataByEnergy?type_of_renewable_energy_code=1&state_code=36&year=2023&Format=JSON
Status: 200
Content-Type: application/json; charset=utf-8
Response:
{"data":[{"type_of_renewable_energy":"Solar Power","year":2023,"month":"December","state":"All India","category":"Ground Mounted Solar Power","value":"56920.20"},{"type_of_renewable_energy":"Solar Power","year":2023,"month":"December","state":"All India","category":"Rooftop Solar Power","value":"11078.94"},{"type_of_renewable_energy":"Solar Power","year":2023,"month":"December","state":"All India","category":" Hybrid Solar Component","value":"2571.96"},{"type_of_renewable_energy":"Solar Power","year":2023,"month":"December","state":"All India","category":"Off-Grid Solar Power/KUSUM","value":"2748.39"},{"type_of_renewable_energy":"Solar Power","year":2023,"month":"December","state":"All India","category":"Solar Power Total","value":"73319.50"},{"type_of_renewable_energy":"Solar Power","year":2023,"month":"November","state":"All India","category":"Ground Mounted Solar Power","value":"55958.18"},{"type_of_renewable_energy":"Solar Power","year":2023,"month":"November","state":"All India","category":"Rooftop Solar Power","value":"11078.94"},{"type_of_renewable_energy":"Solar Power","year":2023,"month":"November","state":"All India","category":" Hybrid Solar Component","value":"2570.96"},{"type_of_renewable_energy":"Solar Power","year":2023,"month":"November","state":"All India","category":"Off-Grid Solar Power/KUSUM","value":"2703.53"},{"type_of_renewable_energy":"Solar Power","year":2023,"month":"November","state":"All India","category":"Solar Power Total","value":"72311.62"}],"meta_data":{"page":1,"totalRecords":60,"totalPages":6,"recordPerPage":10},"msg":"Data fetched successfully","statusCode":true}
================================================================================

,type_of_renewable_energy,year,month,state,category,value
0,Solar Power,2023,December,All India,Ground Mounted Solar Power,56920.20
1,Solar Power,2023,December,All India,Rooftop Solar Power,11078.94
2,Solar Power,2023,December,All India,Hybrid Solar Component,2571.96
3,Solar Power,2023,December,All India,Off-Grid Solar Power/KUSUM,2748.39
4,Solar Power,2023,December,All India,Solar Power Total,73319.50
5,Solar Power,2023,November,All India,Ground Mounted Solar Power,55958.18
6,Solar Power,2023,November,All India,Rooftop Solar Power,11078.94
7,Solar Power,2023,November,All India,Hybrid Solar Component,2570.96
8,Solar Power,2023,November,All India,Off-Grid Solar Power/KUSUM,2703.53
9,Solar Power,2023,November,All India,Solar Power Total,72311.62

---
## Output Formats

All functions support `format="dict"` (default), `format="df"` (pandas DataFrame), or `format="csv"`.

In [ ]:
csv_str = esankhyiki.get_data("PLFS", {
    "indicator_code": 3,
    "frequency_code": 1,
    "year_type_code":1,
    "year": "2023-24",
    "state_code": 99,
    "gender_code": 3,
    "age_code": 1,
    "sector_code": 3,
}, format="csv")

print(csv_str[:600])

---
## Error Handling

In [ ]:
# Typo in dataset name - fuzzy suggestion
try:
    esankhyiki.get_indicators("plfs_data")
except InvalidDatasetError as e:
    print(e)

In [ ]:
# Missing required parameter
try:
    esankhyiki.get_metadata("PLFS", frequency_code=1)
except InvalidFilterError as e:
    print(e)

In [ ]:
# Invalid filter parameter name
try:
    esankhyiki.get_data("PLFS", {
        "indicator_code": 1,
        "frequency_code": 1,
        "typo_param": "hello",
    })
except InvalidFilterError as e:
    print(e)