# esankhyiki - Examples

Python client for India's National Statistical Office (MoSPI) data portal.
Access indicators across 19 datasets: employment, prices, GDP, health, education, environment, and more.

```bash
pip install mospi-esankhyiki[pandas]
```

In [1]:
import warnings
warnings.filterwarnings('ignore')
import esankhyiki
from esankhyiki.exceptions import InvalidDatasetError, InvalidFilterError, APIError, NoDataError

---
## Available Datasets

In [2]:
esankhyiki.list_datasets(format="df")

     dataset
0       PLFS
1        CPI
2        IIP
3        ASI
4        NAS
5        WPI
6     ENERGY
7      AISHE
8      ASUSE
9     GENDER
10      NFHS
11  ENVSTATS
12       RBI
13     NSS77
14     NSS78
15   CPIALRL
16      HCES
17       TUS
18        EC

---
## PLFS - Periodic Labour Force Survey

Covers labour force participation, unemployment, worker population ratio, wages.
Use `get_indicators` to see what indicator codes are available, `get_metadata` to see valid filter values for a given indicator.

In [3]:
# Indicators grouped by frequency_code
indicators = esankhyiki.get_indicators("PLFS")
for group, items in indicators["indicators_by_frequency"].items():
    print(f"\n{group}:")
    for item in items:
        print(f"  {item['indicator_code']}: {item.get('indicator_name', item.get('description', ''))}")

frequency_code_1_Annual:
  1: LFPR (Labour Force Participation Rate, in per cent)
  2: WPR (Worker Population Ratio, in per cent)
  3: UR (Unemployment Rate, in per cent)
  4: Percentage distribution of workers
  5: Percentage of regular wage/ salaried employees with employment condition as
  6: Average wage/salary earnings (Rs. 0.00) during the preceding calendar month from regular wage/salaried employment
  7: Average wage earnings (Rs. 0.00) per day from casual labour work other than public works
  8: Average gross earnings (Rs. 0.00) during last 30 days from self-employment

frequency_code_2_Quarterly:
  1: LFPR (Labour Force Participation Rate, in per cent)
  2: WPR (Worker Population Ratio, in per cent)
  3: UR (Unemployment Rate, in per cent)
  4: Percentage distribution of workers

frequency_code_3_Monthly:
  1: LFPR (Labour Force Participation Rate, in per cent)
  2: WPR (Worker Population Ratio, in per cent)
  3: UR (Unemployment Rate, in per cent)

In [5]:
# Valid filter values for Unemployment Rate (indicator_code=3), Annual (frequency_code=1)
metadata = esankhyiki.get_metadata("PLFS", indicator_code=3, frequency_code=1, year_type_code=1)
for key, values in metadata["filter_values"]["data"].items():
    print(f"\n{key}:")
    for v in values[:4]:
        print(f"  {v}")

year_type:
  {'description': 'Calendar Year', 'year_type_code': 2}
  {'description': 'Agriculture Year', 'year_type_code': 1}

year:
  {'year': '2025'}
  {'year': '2024'}
  {'year': '2023-24'}
  {'year': '2023'}

age:
  {'age_code': 1, 'description': '15 years and above'}
  {'age_code': 2, 'description': '15-29 years'}
  {'age_code': 3, 'description': '15-59 years'}
  {'age_code': 4, 'description': 'all'}

education:
  {'description': '1.not literate', 'education_code': 1}
  {'description': '2.literate & upto primary', 'education_code': 2}
  {'description': '3.middle', 'education_code': 3}
  {'description': '4.secondary', 'education_code': 4}

gender:
  {'description': 'male', 'gender_code': 1}
  {'description': 'female', 'gender_code': 2}
  {'description': 'person', 'gender_code': 3}

religion:
  {'description': 'all', 'religion_code': 1}
  {'description': 'Hinduism', 'religion_code': 2}
  {'description': 'Islam', 'religion_code': 3}
  {'description': 'Christianity', 'religion_code': 4}

sector:
  {'description': 'rural', 'sector_code': 1}
  {'description': 'urban', 'sector_code': 2}
  {'description': 'rural + urban', 'sector_code': 3}

social_category:
  {'description': 'all', 'social_category_code': 1}
  {'description': 'scheduled tribe', 'social_category_code': 2}
  {'description': 'scheduled caste', 'social_category_code': 3}
  {'description': 'other backward class', 'social_category_code': 4}

state:
  {'state_code': 99, 'description': 'All India'}
  {'state_code': 31, 'description': 'Andaman & Nicobar Islands'}
  {'state_code': 1, 'description': 'Andhra Pradesh'}
  {'state_code': 2, 'description': 'Arunachal Pradesh'}

weekly_status:
  {'description': 'PS+SS', 'weekly_status_code': 1}
  {'description': 'CWS', 'weekly_status_code': 2}

In [6]:
# Unemployment Rate - All India, all years, both sectors
esankhyiki.get_data("PLFS", {
    "indicator_code": 3,
    "frequency_code": 1,
    "year_type_code":1,
    "state_code": 99,     # 99 = All India
    "gender_code": 3,     # 3 = Person
    "age_code": 1,        # 1 = 15 years and above
    "sector_code": 3,     # 3 = rural + urban
}, format="df")

,year_type,year,frequency,indicator,state,gender,sector,AgeGroup,weekly_status,religion,socialGroup,General_Education,quarter,month,value,unit
0,Agriculture Year,2017-18,Annually,"UR (Unemployment Rate, in per cent)",All India,person,rural + urban,15 years and above,PS+SS,all,other backward class,all,all,None,5.9,%
1,Agriculture Year,2017-18,Annually,"UR (Unemployment Rate, in per cent)",All India,person,rural + urban,15 years and above,CWS,all,all,all,all,None,8.7,%
2,Agriculture Year,2017-18,Annually,"UR (Unemployment Rate, in per cent)",All India,person,rural + urban,15 years and above,PS+SS,all,scheduled caste,all,all,None,6.2,%
3,Agriculture Year,2017-18,Annually,"UR (Unemployment Rate, in per cent)",All India,person,rural + urban,15 years and above,PS+SS,all,scheduled tribe,all,all,None,4.2,%
4,Agriculture Year,2017-18,Annually,"UR (Unemployment Rate, in per cent)",All India,person,rural + urban,15 years and above,PS+SS,all,all,9.secondary & above,all,None,11.4,%
5,Agriculture Year,2017-18,Annually,"UR (Unemployment Rate, in per cent)",All India,person,rural + urban,15 years and above,PS+SS,all,all,6.diploma/ certificate course,all,None,19.8,%
6,Agriculture Year,2017-18,Annually,"UR (Unemployment Rate, in per cent)",All India,person,rural + urban,15 years and above,PS+SS,all,all,7.graduate,all,None,17.2,%
7,Agriculture Year,2017-18,Annually,"UR (Unemployment Rate, in per cent)",All India,person,rural + urban,15 years and above,PS+SS,all,all,5.higher secondary,all,None,10.3,%
8,Agriculture Year,2017-18,Annually,"UR (Unemployment Rate, in per cent)",All India,person,rural + urban,15 years and above,PS+SS,all,all,8.post graduate & above,all,None,14.6,%
9,Agriculture Year,2017-18,Annually,"UR (Unemployment Rate, in per cent)",All India,person,rural + urban,15 years and above,PS+SS,all,others,all,all,None,6.7,%

---
## CPI - Consumer Price Index

Multiple base years (2010, 2012, 2024) and two levels: Group and Item.

In [8]:
# Available base years, levels, and series
esankhyiki.get_indicators("CPI", format="df")

   base_year  level   series
0       2010  Group  Current
1       2010  Group     Back
2       2010   Item  Current
3       2010   Item     Back
4       2012  Group  Current
5       2012  Group     Back
6       2012   Item  Current
7       2012   Item     Back
8       2024  Group  Current
9       2024  Group     Back
10      2024   Item  Current
11      2024   Item     Back

In [9]:
# Filter values for base_year=2012, Group level
metadata = esankhyiki.get_metadata("CPI", base_year="2012", level="Group", series="Current", format="df")
metadata

,series,year,month_code,month_name,state_code,state_name,sector_code,sector_name,group_code,group_name,subgroup_code,subgroup_name
0,Current,2025,1,January,99,All India,1,Rural,0,General,0.99,General-Overall
1,Current,2025,1,January,99,All India,1,Rural,1,General,1.1.01,Cereals and Products
2,Current,2025,1,January,99,All India,1,Rural,1,General,1.1.02,Meat and Fish
3,Current,2025,1,January,99,All India,1,Rural,1,General,1.1.03,Egg
4,Current,2025,1,January,99,All India,1,Rural,1,General,1.1.04,Milk and Products
...,...,...,...,...,...,...,...,...,...,...,...,...
8951035,Back,2011,12,December,19,West Bengal,3,Combined,6,Consumer Food Price,6.1.04,Recreation and Amusement
8951036,Back,2011,12,December,19,West Bengal,3,Combined,6,Consumer Food Price,6.1.05,Education
8951037,Back,2011,12,December,19,West Bengal,3,Combined,6,Consumer Food Price,6.1.06,Personal Care and Effects
8951038,Back,2011,12,December,19,West Bengal,3,Combined,6,Consumer Food Price,6.99,Miscellaneous-Overall
8951039,Back,2011,12,December,19,West Bengal,3,Combined,7,Consumer Food Price,7.99,Consumer Food Price-Overall

In [10]:
# CPI Group index, base year 2012, year 2024
esankhyiki.get_data("CPI", {
    "base_year": "2012",
    "series": "Current",
    "year": "2024",
}, format="df")

,baseyear,year,month,state,sector,group,subgroup,index,inflation,status
0,2012,2024,December,All India,Rural,Consumer Food Price,Consumer Food Price-Overall,204.7,8.65,F
1,2012,2024,December,All India,Rural,Miscellaneous,Transport and Communication,176.7,2.85,F
2,2012,2024,December,All India,Rural,Miscellaneous,Education,192.2,3.72,F
3,2012,2024,December,All India,Rural,Miscellaneous,Miscellaneous-Overall,190.8,4.26,F
4,2012,2024,December,All India,Rural,Miscellaneous,Household Goods and Services,187.0,2.47,F
5,2012,2024,December,All India,Rural,Miscellaneous,Health,200.2,4.00,F
6,2012,2024,December,All India,Rural,Miscellaneous,Personal Care and Effects,206.3,9.68,F
7,2012,2024,December,All India,Rural,Miscellaneous,Recreation and Amusement,181.5,2.54,F
8,2012,2024,December,All India,Rural,Fuel and Light,Fuel and Light-Overall,182.3,-0.44,F
9,2012,2024,December,All India,Rural,Housing,Housing-Overall,NaN,NaN,F

---
## NAS - National Accounts Statistics (GDP)

Annual and quarterly GDP, GVA, consumption, capital formation by industry and institutional sector.

In [11]:
esankhyiki.get_indicators("NAS", format="df")

    indicator_code                                 description
0                1                           Gross Value Added
1                2                       Net Taxes on Products
2                3                           Taxes on Products
3                4                       Subsidies on Products
4                5                      Gross Domestic Product
5                6                Consumption of Fixed Capital
6                7                        Net Domestic Product
7                8  Gross Capital Formation by Industry of Use
8                9               Gross Fixed Capital Formation
9               10       Private Final Consumption Expenditure
10              11    Government Final Consumption Expenditure
11              12                             Change in Stock
12              13                                   Valuables
13              14                Export of Goods and Services
14              15                Import of Goods and Services
15              16      Primary Income Receivable Net From Row
16              17                       Gross National Income
17              18        Other Current Transfers Net From Row
18              19            Gross National Disposable Income
19              20                                Gross Saving
20              21                             GVA Growth Rate
21              22                             GDP Growth Rate

In [12]:
# Filter values for GVA by industry (indicator_code=1), base year 2022-23
metadata = esankhyiki.get_metadata("NAS", indicator_code=1, base_year="2022-23", series="Current", frequency_code=1)
for key, values in metadata.items():
    if isinstance(values, list):
        print(f"{key}: {values[:3]}")

year: [{'year': '2025-26'}, {'year': '2024-25'}, {'year': '2023-24'}]
revision: [{'revision_code': 2, 'revision_name': 'Second Advance Estimates'}, {'revision_code': 4, 'revision_name': 'First Revised Estimates'}, {'revision_code': 8, 'revision_name': 'Final Estimates'}]
industry: [{'industry_code': 1, 'industry_name': 'Agriculture, Livestock, Forestry and Fishing'}, {'industry_code': 2, 'industry_name': 'Mining and Quarrying'}, {'industry_code': 3, 'industry_name': 'Manufacturing'}]
subindustry: [{'subindustry_code': 1, 'subindustry_name': 'Crops', 'industry_code': 1}, {'subindustry_code': 2, 'subindustry_name': 'Livestock', 'industry_code': 1}, {'subindustry_code': 3, 'subindustry_name': 'Forestry and Logging', 'industry_code': 1}]
institutional_sector: [{'institutional_code': 1, 'institutional_name': 'Public Non-Financial Corporations'}, {'institutional_code': 2, 'institutional_name': 'Private Non-Financial Corporations'}, {'institutional_code': 3, 'institutional_name': 'Public Financial Corporations'}]

In [13]:
# GVA by industry, current prices, latest estimates
esankhyiki.get_data("NAS", {
    "indicator_code": 1,
    "base_year": "2022-23",
    "series": "Current",
    "frequency_code": 1,
    "year": "2024-25",
}, format="df")

,base_year,series,year,indicator,frequency,revision,industry,subindustry,institutional_sector,quarter,current_price,constant_price,unit
0,2022-23,Current,2024-25,Gross Value Added,Annual,First Revised Estimates,NaN,NaN,Public Non-Financial Corporations,None,1551904.3111790416,NaN,₹ Crore
1,2022-23,Current,2024-25,Gross Value Added,Annual,First Revised Estimates,NaN,NaN,Private Non-Financial Corporations,None,9555601.402799515,NaN,₹ Crore
2,2022-23,Current,2024-25,Gross Value Added,Annual,First Revised Estimates,NaN,NaN,Public Financial Corporations,None,780342.4093269374,NaN,₹ Crore
3,2022-23,Current,2024-25,Gross Value Added,Annual,First Revised Estimates,NaN,NaN,Private Financial Corporations,None,1059339.3228545364,NaN,₹ Crore
4,2022-23,Current,2024-25,Gross Value Added,Annual,First Revised Estimates,NaN,NaN,General Government,None,2656799.960246522,NaN,₹ Crore
5,2022-23,Current,2024-25,Gross Value Added,Annual,First Revised Estimates,NaN,NaN,Households Including NPISH,None,13250480.021178257,NaN,₹ Crore
6,2022-23,Current,2024-25,Gross Value Added,Annual,First Revised Estimates,NaN,NaN,Total Gross Value Added,None,28854467.42758481,NaN,₹ Crore
7,2022-23,Current,2024-25,Gross Value Added,Annual,First Revised Estimates,"Agriculture, Livestock, Forestry and Fishing",Crops,NaN,None,3487514.5392785612,3113280.9316670736,₹ Crore
8,2022-23,Current,2024-25,Gross Value Added,Annual,First Revised Estimates,"Agriculture, Livestock, Forestry and Fishing",Livestock,NaN,None,1387062.690777359,1278634.3400525874,₹ Crore
9,2022-23,Current,2024-25,Gross Value Added,Annual,First Revised Estimates,"Agriculture, Livestock, Forestry and Fishing",Forestry and Logging,NaN,None,408682.0267620707,414487.83170621865,₹ Crore

---
## IIP - Index of Industrial Production

Monthly and annual industrial output across manufacturing, mining, and electricity sectors.

In [14]:
# Available categories and years for IIP annual
metadata = esankhyiki.get_metadata("IIP", base_year="2011-12", frequency="Annually")
metadata

{'financial_year': [{'financial_year': '2024-25'},
  {'financial_year': '2023-24'},
  {'financial_year': '2022-23'},
  {'financial_year': '2021-22'},
  {'financial_year': '2020-21'},
  {'financial_year': '2019-20'},
  {'financial_year': '2018-19'},
  {'financial_year': '2017-18'},
  {'financial_year': '2016-17'},
  {'financial_year': '2015-16'},
  {'financial_year': '2014-15'},
  {'financial_year': '2013-14'},
  {'financial_year': '2012-13'}],
 'type': [{'type': 'Use-based category'},
  {'type': 'Sectoral'},
  {'type': 'General'}],
 'category': [{'category_code': 1,
   'category_name': 'Mining',
   'type': 'Sectoral'},
  {'category_code': 2, 'category_name': 'Manufacturing', 'type': 'Sectoral'},
  {'category_code': 3, 'category_name': 'Electricity', 'type': 'Sectoral'},
  {'category_code': 4, 'category_name': 'General', 'type': 'General'},
  {'category_code': 5,
   'category_name': 'Primary Goods',
   'type': 'Use-based category'},
  {'category_code': 6,
   'category_name': 'Capital Goods',
   'type': 'Use-based category'},
  {'category_code': 7,
   'category_name': 'Intermediate Goods',
   'type': 'Use-based category'},
  {'category_code': 8,
   'category_name': 'Infrastructure/ Construction Goods',
   'type': 'Use-based category'},
  {'category_code': 9,
   'category_name': 'Consumer Durables',
   'type': 'Use-based category'},
  {'category_code': 10,
   'category_name': 'Consumer Non-durables',
   'type': 'Use-based category'}],
 'subcategory': [{'subcategory_code': '022011-1210',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Food Products'},
  {'subcategory_code': '022011-1211',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Beverages'},
  {'subcategory_code': '022011-1212',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Tobacco Products'},
  {'subcategory_code': '022011-1213',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Textiles'},
  {'subcategory_code': '022011-1214',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Wearing Apparel'},
  {'subcategory_code': '022011-1215',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Leather and Related Products'},
  {'subcategory_code': '022011-1216',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Wood and Products of Wood and Cork, Except Furniture; Manufacture of Articles of Straw and Plaiting Materials'},
  {'subcategory_code': '022011-1217',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Paper and Paper Products'},
  {'subcategory_code': '022011-1218',
   'category_code': 2,
   'subcategory_name': 'Printing and Reproduction of Recorded Media'},
  {'subcategory_code': '022011-1219',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Coke and Refined Petroleum Products'},
  {'subcategory_code': '022011-1220',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Chemicals and Chemical Products'},
  {'subcategory_code': '022011-1221',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Pharmaceuticals, Medicinal Chemical and Botanical Products'},
  {'subcategory_code': '022011-1222',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Rubber and Plastics Products'},
  {'subcategory_code': '022011-1223',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Other Non-metallic Mineral Products'},
  {'subcategory_code': '022011-1224',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Basic Metals'},
  {'subcategory_code': '022011-1225',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Fabricated Metal Products, Except Machinery and Equipment'},
  {'subcategory_code': '022011-1226',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Computer, Electronic and Optical Products'},
  {'subcategory_code': '022011-1227',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Electrical Equipment'},
  {'subcategory_code': '022011-1228',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Machinery and Equipment N.e.c.'},
  {'subcategory_code': '022011-1229',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Motor Vehicles, Trailers and Semi-trailers'},
  {'subcategory_code': '022011-1230',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Other Transport Equipment'},
  {'subcategory_code': '022011-1231',
   'category_code': 2,
   'subcategory_name': 'Manufacture of Furniture'},
  {'subcategory_code': '022011-1232',
   'category_code': 2,
   'subcategory_name': 'Other Manufacturing'}]}

In [15]:
# IIP annual, 2023-24
esankhyiki.get_data("IIP", {
    "base_year": "2011-12",
    "financial_year": "2023-24",
}, format="df")

,base_year,year,type,category,sub_category,index,growth_rate
0,2011-12,2023-24,General,General,,146.7,5.9
1,2011-12,2023-24,Sectoral,Mining,,128.9,7.5
2,2011-12,2023-24,Sectoral,Manufacturing,Manufacture of Food Products,134.5,1.6
3,2011-12,2023-24,Sectoral,Manufacturing,Manufacture of Beverages,110.9,5.1
4,2011-12,2023-24,Sectoral,Manufacturing,Manufacture of Tobacco Products,81.1,-8.3
5,2011-12,2023-24,Sectoral,Manufacturing,Manufacture of Textiles,107.6,0.1
6,2011-12,2023-24,Sectoral,Manufacturing,Manufacture of Wearing Apparel,109.9,-14.1
7,2011-12,2023-24,Sectoral,Manufacturing,Manufacture of Leather and Related Products,95.0,-1.0
8,2011-12,2023-24,Sectoral,Manufacturing,Manufacture of Wood and Products of Wood and C...,98.3,-5.9
9,2011-12,2023-24,Sectoral,Manufacturing,Manufacture of Paper and Paper Products,79.4,-3.6

---
## GENDER - Gender Statistics

147 indicators covering demographics, health, education, labour, financial inclusion, and crimes against women.

In [17]:
indicators = esankhyiki.get_indicators("GENDER")
print(f"Total indicators: {len(indicators)}\n")
for i in indicators[:10]:
    print(f"  {i['indicator_code']}: {i['description']}")

Total indicators: 147

  1: Trend in Population
  2: Sex Ratio
  3: Average Annual Growth Rate of Population
  4: Percentage Distribution of Projected Population
  5: Sex ratio in context of developmental planning
  6: State-wise Sex Ratio
  7: Sex ratio at birth for bigger States based on Sample Registration System
  8: General Fertility Rate
  9: Age-specific Fertility rate
  10: Total Fertility Rate

In [18]:
# Sex ratio (indicator_code=2)
esankhyiki.get_data("GENDER", {"indicator_code": 2}, format="df")

   year                    state/UT  indicator value unit
0  1951                   All India  Sex Ratio   946    %
1  1951  Andaman & Nicobar  Islands  Sex Ratio   625    %
2  1951              Andhra Pradesh  Sex Ratio   986    %
3  1951           Arunachal Pradesh  Sex Ratio     -    %
4  1951                       Assam  Sex Ratio   868    %
5  1951                       Bihar  Sex Ratio  1000    %
6  1951                  Chandigarh  Sex Ratio   781    %
7  1951                Chhattisgarh  Sex Ratio  1024    %
8  1951        Dadra & Nagar Haveli  Sex Ratio   946    %
9  1951                 Daman & Diu  Sex Ratio  1125    %

---
## ENVSTATS - Environment Statistics

124 indicators covering climate, water, forests, biodiversity, pollution, and natural disasters.

In [19]:
indicators = esankhyiki.get_indicators("ENVSTATS")
print(f"Total indicators: {len(indicators)}\n")
for i in indicators[:10]:
    print(f"  {i['indicator_code']}: {i.get('description', i.get('label', ''))}")

Total indicators: 124

  1: Annual and Seasonal Mean Temperature
  2: Annual and Seasonal Minimum and Maximum Temperature
  3: Annual and Monthly Rainfall
  4: Wetland distribution in India
  5: Number and Area of Wetlands
  6: Water Sheds in India
  7: Catchment Area of major River Basins
  8: Length of Coastline and Coastal Population of India
  9: Occurrence of Major Soils in India
  10: Category-wise distribution of land degradation in different States of India

In [20]:
# Mean temperature trend (indicator_code=1)
esankhyiki.get_data("ENVSTATS", {"indicator_code": 1}, format="df")

     year                             indicator     period    value unit
0    2024  Annual and Seasonal Mean Temperature     Annual  25.7431   °C
1    2024  Annual and Seasonal Mean Temperature    Jan-Feb  19.7385   °C
2    2024  Annual and Seasonal Mean Temperature    Mar-May  28.3522   °C
3    2024  Annual and Seasonal Mean Temperature  June-Sept  28.7166   °C
4    2024  Annual and Seasonal Mean Temperature    Oct-Dec  23.1724   °C
..    ...                                   ...        ...      ...  ...
115  2001  Annual and Seasonal Mean Temperature     Annual  25.0501   °C
116  2001  Annual and Seasonal Mean Temperature    Jan-Feb  19.4017   °C
117  2001  Annual and Seasonal Mean Temperature    Mar-May  27.7716   °C
118  2001  Annual and Seasonal Mean Temperature  June-Sept  27.7377   °C
119  2001  Annual and Seasonal Mean Temperature    Oct-Dec  22.5326   °C

[120 rows x 5 columns]

---
## RBI - Foreign Trade and Exchange Rates

39 indicators on balance of payments, forex reserves, exchange rates (155 currencies), NRI deposits.

In [21]:
indicators = esankhyiki.get_indicators("RBI")
for i in indicators:
    print(f"  {i['indicator_code']}: {i['label']}")

  22: Balance of Payments ‑ Indicators
  24: Broad Commodity Composition of India's Merchandise Trade ‑ Oil and Non oil Exports and Imports ‑ Rupees
  42: Broad Commodity Composition of India’s Merchandise Trade - Oil and Non-Oil Exports and Imports - US Dollar
  1: Direction of Foreign Trade ‑ Rupees
  11: Direction of Foreign Trade ‑ US Dollars
  32: Exchange Rate of the Indian Rupee Vis‑a‑Vis the SDR, US Dollar, Pound Sterling, D.M./Euro and Japanese Yen (Calendar Year ‑ Annual Average)
  31: Exchange Rate of the Indian Rupee Vis‑A‑Vis the SDR, US Dollar, Pound Sterling, D.M./Euro and Japanese Yen (Financial Year ‑ Annual Average and End‑Year Rates)
  35: Exchange Rate of the Indian Rupee vis-à-vis the SDR, US Dollar, Pound Sterling, Euro and Japanese Yen (High and Low During the Month)
  33: Exchange Rate of the Indian Rupee vis-à-vis the SDR, US Dollar, Pound Sterling, Euro and Japanese Yen (Monthly Average and end-Month Rates)
  43: EXPORTS OF MAJOR COMMODITIES - RUPEES
  44: EXPORTS OF MAJOR COMMODITIES - US Dollars
  2: Exports of Select Commodities to Principal Countries ‑ Rupees
  20: Exports of Select Commodities to Principal Countries ‑ US Dollars
  27: External Debt of India ‑ Quarterly
  48: Foreign Exchange Reserve Annual
  47:  Foreign Exchange Reserve Monthly
  29: Forex Rates ‑ Month‑High / Month‑Low
  34: Forward Premia (Inter‑Bank) (Monthly Average)
  45: Imports of Major Commodities - Rupees
  46: Imports of Major Commodities - US Dollars
  26: India's External Debt ‑ Rupees (End‑March)
  25: India's External Debt ‑ US Dollars (End‑March)
  13: India's Foreign Trade – Rupees
  17: India's Foreign Trade – Rupees-Annual
  12: India's Foreign Trade ‑ US Dollars
  16: India's Foreign Trade ‑ US Dollars - Annual
  10: India’s Overall Balance of Payments – Quarterly – Rupees
  4: India's Overall Balance of Payments ‑ Quarterly ‑ US Dollars
  6: India's Overall Balance of Payments – Rupees
  5: India's Overall Balance of Payments ‑ US Dollars
  14: Invisibles by Category of Transactions – Rupees
  9: Invisibles by Category of Transactions – US Dollars
  7: Key Components of India's Balance of Payments – Rupees
  8: Key Components of India's Balance of Payments ‑ US Dollars
  37: Monthly Average Exchange Rate (155 Currencies)
  36: Monthly Average Exchange Rates (EURO, GBP, JPY, USD)
  40: NRI Deposits - Outstandings and Inflows(+) / Outflows(-)
  28: Sale/ Purchase of U.S. Dollar by the RBI
  30: Turnover in Foreign Exchange Market

In [22]:
# Get valid sub_indicator_codes for Balance of Payments (indicator_code=22)
metadata = esankhyiki.get_metadata("RBI", sub_indicator_code=22)
metadata

[{'sub_indicator_code': 22,
  'label': 'Balance of Payments ‑ Indicators',
  'dimensions': {'year': [{'id': '2024-25', 'label': '2024-25'},
    {'id': '2023-24', 'label': '2023-24'},
    {'id': '2022-23', 'label': '2022-23'},
    {'id': '2021-22', 'label': '2021-22'},
    {'id': '2020-21', 'label': '2020-21'},
    {'id': '2019-20', 'label': '2019-20'},
    {'id': '2018-19', 'label': '2018-19'},
    {'id': '2017-18', 'label': '2017-18'},
    {'id': '2016-17', 'label': '2016-17'},
    {'id': '2015-16', 'label': '2015-16'},
    {'id': '2014-15', 'label': '2014-15'},
    {'id': '2013-14', 'label': '2013-14'},
    {'id': '2012-13', 'label': '2012-13'},
    {'id': '2011-12', 'label': '2011-12'},
    {'id': '2010-11', 'label': '2010-11'},
    {'id': '2009-10', 'label': '2009-10'},
    {'id': '2008-09', 'label': '2008-09'},
    {'id': '2007-08', 'label': '2007-08'},
    {'id': '2006-07', 'label': '2006-07'},
    {'id': '2005-06', 'label': '2005-06'},
    {'id': '2004-05', 'label': '2004-05'},
    {'id': '2003-04', 'label': '2003-04'},
    {'id': '2002-03', 'label': '2002-03'},
    {'id': '2001-02', 'label': '2001-02'},
    {'id': '2000-01', 'label': '2000-01'},
    {'id': '1999-00', 'label': '1999-00'},
    {'id': '1998-99', 'label': '1998-99'},
    {'id': '1997-98', 'label': '1997-98'},
    {'id': '1996-97', 'label': '1996-97'},
    {'id': '1995-96', 'label': '1995-96'},
    {'id': '1994-95', 'label': '1994-95'},
    {'id': '1993-94', 'label': '1993-94'},
    {'id': '1992-93', 'label': '1992-93'},
    {'id': '1991-92', 'label': '1991-92'},
    {'id': '1990-91', 'label': '1990-91'},
    {'id': '1989-90', 'label': '1989-90'},
    {'id': '1988-89', 'label': '1988-89'},
    {'id': '1987-88', 'label': '1987-88'},
    {'id': '1986-87', 'label': '1986-87'},
    {'id': '1985-86', 'label': '1985-86'},
    {'id': '1984-85', 'label': '1984-85'},
    {'id': '1983-84', 'label': '1983-84'},
    {'id': '1982-83', 'label': '1982-83'},
    {'id': '1981-82', 'label': '1981-82'},
    {'id': '1980-81', 'label': '1980-81'},
    {'id': '1979-80', 'label': '1979-80'},
    {'id': '1978-79', 'label': '1978-79'},
    {'id': '1977-78', 'label': '1977-78'},
    {'id': '1976-77', 'label': '1976-77'},
    {'id': '1975-76', 'label': '1975-76'},
    {'id': '1974-75', 'label': '1974-75'},
    {'id': '1973-74', 'label': '1973-74'},
    {'id': '1972-73', 'label': '1972-73'},
    {'id': '1971-72', 'label': '1971-72'},
    {'id': '1970-71', 'label': '1970-71'}],
   'balance_of_payments': [{'id': 1,
     'label': 'Capital account',
     'children': {'trade_category': [{'id': 5,
        'label': 'Foreign Investment/ Exports',
        'children': {}},
       {'id': 6, 'label': 'Foreign Investment/ GDP', 'children': {}}]}},
    {'id': 2,
     'label': 'Current account',
     'children': {'trade_category': [{'id': 1,
        'label': 'CAD/ GDP',
        'children': {}},
       {'id': 2,
        'label': 'Current Receipts/ Current Payments',
        'children': {}},
       {'id': 3, 'label': 'Current Receipts/ GDP', 'children': {}}]}},
    {'id': 3,
     'label': 'Invisibles',
     'children': {'trade_category': [{'id': 8,
        'label': 'Net/ GDP',
        'children': {}},
       {'id': 9, 'label': 'Payments/GDP', 'children': {}},
       {'id': 10, 'label': 'Receipts/GDP', 'children': {}}]}},
    {'id': 4,
     'label': 'Trade',
     'children': {'trade_category': [{'id': 4,
        'label': 'Exports/ GDP',
        'children': {}},
       {'id': 7, 'label': 'Imports/ GDP', 'children': {}}]}},
    {'id': 5,
     'label': 'Import cover of Reserves (in months)',
     'children': {'trade_category': []}}]}}]

In [23]:
# Balance of Payments
esankhyiki.get_data("RBI", {"indicator_code": 22}, format="df")

,indicator,year,trade_category,balance_of_payments,value,unit
0,Balance of Payments ‑ Indicators,2024-25,Current Receipts/ Current Payments,Current account,97.76,%
1,Balance of Payments ‑ Indicators,2024-25,Foreign Investment/ Exports,Capital account,1.02,%
2,Balance of Payments ‑ Indicators,2024-25,Receipts/GDP,Invisibles,14.75,%
3,Balance of Payments ‑ Indicators,2024-25,Current Receipts/ GDP,Current account,26.04,%
4,Balance of Payments ‑ Indicators,2024-25,Net/ GDP,Invisibles,6.75,%
5,Balance of Payments ‑ Indicators,2024-25,Payments/GDP,Invisibles,8.00,%
6,Balance of Payments ‑ Indicators,2024-25,CAD/ GDP,Current account,-0.60,%
7,Balance of Payments ‑ Indicators,2024-25,Imports/ GDP,Trade,18.65,%
8,Balance of Payments ‑ Indicators,2024-25,Exports/ GDP,Trade,11.30,%
9,Balance of Payments ‑ Indicators,2024-25,Foreign Investment/ GDP,Capital account,0.12,%

---
## EC - Economic Census

District-level establishment and worker counts across three census editions (EC4/EC5/EC6).

In [24]:
esankhyiki.get_indicators("EC", format="df")

,indicator_code,indicator_name,description
0,1,Sixth Economic Census (EC6) - 2013-14,District-wise establishment and worker counts....
1,2,Fifth Economic Census (EC5) - 2005,District-wise establishment and worker counts....
2,3,Fourth Economic Census (EC4) - 1998,District-wise establishment and worker counts....

In [25]:
# EC6 (2013-14) - available states and filter options
metadata = esankhyiki.get_metadata("EC", indicator_code=1)
metadata

{'state': [{'id': '01', 'name': 'Jammu And Kashmir'},
  {'id': '02', 'name': 'Himachal Pradesh'},
  {'id': '03', 'name': 'Punjab'},
  {'id': '04', 'name': 'Chandigarh'},
  {'id': '05', 'name': 'Uttarakhand'},
  {'id': '06', 'name': 'Haryana'},
  {'id': '07', 'name': 'Nct Of Delhi'},
  {'id': '08', 'name': 'Rajasthan'},
  {'id': '09', 'name': 'Uttar Pradesh'},
  {'id': '10', 'name': 'Bihar'},
  {'id': '11', 'name': 'Sikkim'},
  {'id': '12', 'name': 'Arunachal Pradesh'},
  {'id': '13', 'name': 'Nagaland'},
  {'id': '14', 'name': 'Manipur'},
  {'id': '15', 'name': 'Mizoram'},
  {'id': '16', 'name': 'Tripura'},
  {'id': '17', 'name': 'Meghalaya'},
  {'id': '18', 'name': 'Assam'},
  {'id': '19', 'name': 'West Bengal'},
  {'id': '20', 'name': 'Jharkhand'},
  {'id': '21', 'name': 'Orissa'},
  {'id': '22', 'name': 'Chhattisgarh'},
  {'id': '23', 'name': 'Madhya Pradesh'},
  {'id': '24', 'name': 'Gujarat'},
  {'id': '25', 'name': 'Daman And Diu'},
  {'id': '26', 'name': 'Dadra And Nagar Haveli'},
  {'id': '27', 'name': 'Maharashtra'},
  {'id': '29', 'name': 'Karnataka'},
  {'id': '30', 'name': 'Goa'},
  {'id': '31', 'name': 'Lakshadweep'},
  {'id': '32', 'name': 'Kerala'},
  {'id': '33', 'name': 'Tamilnadu'},
  {'id': '34', 'name': 'Puducherry'},
  {'id': '35', 'name': 'Andaman And Nicobar Islands'},
  {'id': '36', 'name': 'Telangana'},
  {'id': '37', 'name': 'Andhra Pradesh'}],
 'activity': [{'id': '01', 'name': 'Raising Of Livestock'},
  {'id': '02',
   'name': 'Agricultural Services, Hunting, Trapping And Game, Propagation Forestry & Logging And Fishing'},
  {'id': '03', 'name': 'All Agricultural Activities'},
  {'id': '04', 'name': 'Mining And Quarrying'},
  {'id': '05', 'name': 'Manufacturing'},
  {'id': '06', 'name': 'Electricity, Gas & Water'},
  {'id': '07', 'name': 'Construction'},
  {'id': '08', 'name': 'Wholesale Trade'},
  {'id': '09', 'name': 'Retail Trade'},
  {'id': '10', 'name': 'Restaurants & Hotels'},
  {'id': '11', 'name': 'Transport'},
  {'id': '12', 'name': 'Storage & Warehousing'},
  {'id': '13', 'name': 'Communications'},
  {'id': '14',
   'name': 'Financial, Insurance, Real Estate And Business Services'},
  {'id': '15', 'name': 'Community, Social & Personal Services'},
  {'id': '16', 'name': 'Other Activities'},
  {'id': '17', 'name': 'All Non-Agricultural Activities'},
  {'id': '18', 'name': 'All Agricultural & Non-Agricultural Activities'}],
 'nop': [{'id': '1', 'name': 'Perennial'}, {'id': '2', 'name': 'Seasonal'}],
 'sof': [{'id': '1', 'name': 'Assistance under IRDP'},
  {'id': '2', 'name': 'Assistance under other poverty alleviation Programmes'},
  {'id': '3', 'name': 'Borrowing from Institutions'},
  {'id': '4', 'name': 'Borrowing from Non-Institutions'},
  {'id': '5', 'name': 'Self-financing'},
  {'id': '6', 'name': 'Others'}],
 'ownership': [{'id': '1', 'name': 'Private Non-Profit Institutions'},
  {'id': '2', 'name': 'Private Others'},
  {'id': '3', 'name': 'Co-operatives'},
  {'id': '4', 'name': 'Government'}],
 'sector': [{'id': '1', 'name': 'Rural'}, {'id': '2', 'name': 'Urban'}],
 'top5opt': [{'id': '1', 'name': 'Top 5 Districts'},
  {'id': '2', 'name': 'Top 10 Districts'},
  {'id': '3', 'name': 'Top 15 Districts'},
  {'id': '4', 'name': 'Bottom 5 Districts'},
  {'id': '5', 'name': 'Bottom 10 Districts'},
  {'id': '6', 'name': 'Bottom 15 Districts'}]}

In [26]:
# EC6 - top districts in Maharashtra by establishments
esankhyiki.get_data("EC", {
    "indicator_code": 1,
    "state": "27",       # Maharashtra
    "mode": "ranking",
    "top5opt": "2",
}, format="df")

  rank         district establishments
0    1         Kolhapur         570867
1    2             Pune         514469
2    3  Mumbai Suburban         465416
3    4            Thane         438706
4    5           Satara         383647
5    6          Solapur         373286
6    7           Sangli         278060
7    8           Mumbai         261259
8    9           Nagpur         258711
9   10       Ahmadnagar         246417

---
## Output Formats

All functions support `format="dict"` (default), `format="df"` (pandas DataFrame), or `format="csv"`.

In [28]:
csv_str = esankhyiki.get_data("PLFS", {
    "indicator_code": 3,
    "frequency_code": 1,
    "year_type_code":1,
    "year": "2023-24",
    "state_code": 99,
    "gender_code": 3,
    "age_code": 1,
    "sector_code": 3,
}, format="csv")

print(csv_str[:600])

year_type,year,frequency,indicator,state,gender,sector,AgeGroup,weekly_status,religion,socialGroup,General_Education,quarter,month,value,unit
Agriculture Year,2023-24,Annually,"UR (Unemployment Rate, in per cent)",All India,person,rural + urban,15 years and above,PS+SS,all,all,9.secondary & above,all,,7.1,%
Agriculture Year,2023-24,Annually,"UR (Unemployment Rate, in per cent)",All India,person,rural + urban,15 years and above,PS+SS,all,all,all,all,,3.2,%
Agriculture Year,2023-24,Annually,"UR (Unemployment Rate, in per cent)",All India,person,rural + urban,15 years and above,CWS,all,all,all

---
## Error Handling

In [29]:
# Typo in dataset name - fuzzy suggestion
try:
    esankhyiki.get_indicators("plfs_data")
except InvalidDatasetError as e:
    print(e)

Unknown dataset: 'plfs_data'. Valid datasets: PLFS, CPI, IIP, ASI, NAS, WPI, ENERGY, AISHE, ASUSE, GENDER, NFHS, ENVSTATS, RBI, NSS77, NSS78, CPIALRL, HCES, TUS, EC. Did you mean: PLFS, ENVSTATS, NFHS?

In [30]:
# Missing required parameter
try:
    esankhyiki.get_metadata("PLFS", frequency_code=1)
except InvalidFilterError as e:
    print(e)

Missing required params for get_metadata(dataset='PLFS'): ['indicator_code', 'year_type_code']

In [31]:
# Invalid filter parameter name
try:
    esankhyiki.get_data("PLFS", {
        "indicator_code": 1,
        "frequency_code": 1,
        "typo_param": "hello",
    })
except InvalidFilterError as e:
    print(e)

Invalid params: ['typo_param']. Valid params: ['indicator_code', 'frequency_code', 'year_type_code', 'year', 'month_code', 'state_code', 'gender_code', 'age_code', 'sector_code', 'quarter_code', 'weekly_status_code', 'religion_code', 'social_category_code', 'education_code', 'broad_industry_work_code', 'broad_status_employment_code', 'employee_contract_code', 'enterprise_size_code', 'enterprise_type_code', 'industry_section_code', 'nco_division_code', 'nic_group_code', 'limit', 'page', 'Format'].